### ISSUE TITLE
The ConfigureHttpClient method is not supported when creating gRPC clients.

### ISSUE THREAD

**Issue by eerhardt** [dotnet/extensions#4924] opened 2024-02-06 22:35 UTC
### Description

https://github.com/dotnet/extensions/commit/3654748e14445fa794bcdb0d2ebffa46e758603c is breaking using gRPC clients with Http.Resilience. This is a breaking change from 8.1.

### Reproduction Steps

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="8.2.0-preview.24105.1" />

    <PackageReference Include="Google.Protobuf" Version="3.25.2" />
    <PackageReference Include="Grpc.Net.ClientFactory" Version="2.59.0" />
    <PackageReference Include="Grpc.Tools" Version="2.59.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Protos\greet.proto" GrpcServices="Client" />
  </ItemGroup>
  
</Project>
```

```C#
using GrpcGreeter;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.

builder.Services.AddGrpcClient<Greeter.GreeterClient>(o =>
{
    o.Address = new Uri("https://localhost:5001");
});

builder.Services.ConfigureHttpClientDefaults(http =>
{
    // Turn on resilience by default
    http.AddStandardResilienceHandler();
});

var app = builder.Build();

// Configure the HTTP request pipeline.

var summaries = new[]
{
    "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
};

app.MapGet("/hello", (Greeter.GreeterClient client) =>
{
    return "hello";
});

app.Run();
```

greet.proto:
```proto
syntax = "proto3";

option csharp_namespace = "GrpcGreeter";

package greet;

// The greeting service definition.
service Greeter {
  // Sends a greeting
  rpc SayHello (HelloRequest) returns (HelloReply);
}

// The request message containing the user's name.
message HelloRequest {
  string name = 1;
}

// The response message containing the greetings.
message HelloReply {
  string message = 1;
}
```

### Expected behavior

The app should work, like it did when I use `<PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="8.2.0-preview.24105.1" />`

### Actual behavior

The app fails with:

```
An unhandled exception occurred while processing the request.
InvalidOperationException: The ConfigureHttpClient method is not supported when creating gRPC clients. Unable to create client with name 'GreeterClient'.
Grpc.Net.ClientFactory.Internal.GrpcCallInvokerFactory.CreateInvoker(EntryKey key)

Stack Query Cookies Headers Routing
InvalidOperationException: The ConfigureHttpClient method is not supported when creating gRPC clients. Unable to create client with name 'GreeterClient'.
Grpc.Net.ClientFactory.Internal.GrpcCallInvokerFactory.CreateInvoker(EntryKey key)
System.Collections.Concurrent.ConcurrentDictionary<TKey, TValue>.GetOrAdd(TKey key, Func<TKey, TValue> valueFactory)
Grpc.Net.ClientFactory.Internal.GrpcCallInvokerFactory.CreateInvoker(string name, Type type)
Grpc.Net.ClientFactory.Internal.DefaultGrpcClientFactory.CreateClient<TClient>(string name)
Microsoft.Extensions.DependencyInjection.GrpcClientServiceExtensions+<>c__DisplayClass7_0<TClient>.<AddGrpcHttpClient>b__2(IServiceProvider s)
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor<TArgument, TResult>.VisitCallSite(ServiceCallSite callSite, TArgument argument)
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine+<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
lambda_method2(Closure , object , HttpContext )
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

### Regression?

Yes, from 8.1

### Known Workarounds

Don't call `AddStandardResilienceHandler()` on HttpClients that use gRPC.

### Configuration

net8.0

### Other information

cc @martintmk @geeknoid @joperezr @JamesNK

**Comment by joperezr** [comment] 2024-02-06 23:26
@martintmk can you please take a look at this? As specified above, this is a regression and breaking change, and we are preparing to lock for 8.2 release, so time is running out for fixing this. If fixing this is not trivial, I'd suggest reverting the change that introduced the regression for 8.2, and then we can check on how to better fix the original issue without causing a regression for 8.3. Thoughts?

**Comment by martintmk** [comment] 2024-02-07 08:08
@joperezr Let's just revert that fix for 8.2.0, service owners can still disable the timeout as a workaround. 

Unless the restrictions around using `ConfigureHttpClient` is lifted for GRPC clients, I don't see any other way to fix this. (other than manually disabling timeout for `HttpClient`. 

I must say the behavior of `ConfigureHttpClient` is strange, would love know the reason why it is not allowed.

**Comment by eerhardt** [comment] 2024-02-07 15:29
> I must say the behavior of ConfigureHttpClient is strange, would love know the reason why it is not allowed.

+1.

@JamesNK, can you clue us in on why this is restricted?

**Comment by JamesNK** [comment] 2024-02-07 23:22
> > I must say the behavior of ConfigureHttpClient is strange, would love know the reason why it is not allowed.
> 
> +1.
> 
> @JamesNK, can you clue us in on why this is restricted?

Because it has no impact. It's to let the developer know that this configuration they added to the gRPC client won't do anything.

```cs
builder.Services.AddGrpcClient<Greeter.GreeterClient>(o =>
{
    o.Address = new Uri("https://localhost:5001/");
})
.ConfigureHttpClient(options => options.Timeout = TimeSpan.FromSeconds(10)); // no impact
```

However, now that HttpClientFactory has the concept of applying defaults across all clients it isn't as useful. Changes would be to either add an option to gRPC client factory to suppress the error or changing the error to logging.

**Comment by iliar-turdushev** [comment] 2024-04-29 15:03
> However, now that HttpClientFactory has the concept of applying defaults across all clients it isn't as useful. Changes would be to either add an option to gRPC client factory to suppress the error or changing the error to logging.

@JamesNK Are there any updates to the suggestion above (suppress the error or log it)? If not, is there a ticket/item to tract it? Thank you.

**Comment by JamesNK** [comment] 2024-04-30 03:22
There aren't any updates. I've created an issue to track improving gRPC - https://github.com/grpc/grpc-dotnet/issues/2425

I'm really busy so I'm not sure when I'll get time to look at it.

**Comment by iliar-turdushev** [comment] 2024-08-13 15:45
The issue in grpc-dotnet https://github.com/grpc/grpc-dotnet/issues/2425 was fixed in v2.64.0. We can now reintroduce #4770, and it will not cause the current issue when used together with grpc-dotnet >=v2.64.0.

@joperezr @RussKie How do you think if we need to mention in our documentation that our clients need to be on grpc-dotnet >=v2.64.0 not to face the current issue?

**Comment by RussKie** [comment] 2024-08-14 01:17
We could add a note to https://github.com/dotnet/extensions/blob/main/src/Libraries/Microsoft.Extensions.Http.Resilience/README.md (before 
"Install the package" section).
We should also add the same note to https://learn.microsoft.com/dotnet/core/resilience/http-resilience (in "Get started" section perhaps?)

**Comment by iliar-turdushev** [comment] 2024-09-06 07:20
To reproduce the issue on NET Framework 4.6.2 we can use the following steps:

1. Apply to dotnet/extensions locally the following changes from the commit https://github.com/dotnet/extensions/commit/3654748e14445fa794bcdb0d2ebffa46e758603c.

2. Build the solution and publish the packages locally: `.\build.cmd -pack`.

3. Create a new project in a separate solution. Please, note that we are referencing local package Microsoft.Extensions.Http.Resilience 8.10.0-dev. You need to set up NuGet source to use local folder with dotnet/extensions packages and, probably, adjust the version of the package to your local version.

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net462</TargetFramework>
    <SuppressCheckGrpcNetClientFactoryVersion>false</SuppressCheckGrpcNetClientFactoryVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Protos\greet.proto" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="8.10.0-dev" />
    <PackageReference Include="Grpc.Net.ClientFactory" Version="2.62.0" />

    <PackageReference Include="Google.Protobuf" Version="3.27.0" />
    <PackageReference Include="Grpc.Tools" Version="2.62.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Protos\greet.proto" GrpcServices="Client" />
  </ItemGroup>

</Project>
```

4. Add Program.cs file:

```csharp
using GrpcGreeter;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Threading;

namespace ConsoleApp
{
    internal static class Program
    {
        private static void Main(string[] args)
        {
            var serviceCollection = new ServiceCollection();

            serviceCollection.ConfigureHttpClientDefaults(http =>
            {
                http.AddStandardResilienceHandler();
            });

            serviceCollection.AddGrpcClient<Greeter.GreeterClient>(o =>
            {
                o.Address = new Uri("https://localhost:5001");
            });

            var serviceProvider = serviceCollection.BuildServiceProvider();

            var grpcClient = serviceProvider.GetRequiredService<Greeter.GreeterClient>();
        }
    }
}
```

5. Add greet.proto file:

```proto
syntax = "proto3";

option csharp_namespace = "GrpcGreeter";

package greet;

// The greeting service definition.
service Greeter {
  // Sends a greeting
  rpc SayHello (HelloRequest) returns (HelloReply);
}

// The request message containing the user's name.
message HelloRequest {
  string name = 1;
}

// The response message containing the greetings.
message HelloReply {
  string message = 1;
}
```

6. Run the application, you'll get the following exception:

```output
Unhandled Exception: System.InvalidOperationException: The ConfigureHttpClient method is not supported when creating gRPC clients. Unable to create client with name 'GreeterClient'.
   at Grpc.Net.ClientFactory.Internal.GrpcCallInvokerFactory.CreateInvoker(EntryKey key)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Grpc.Net.ClientFactory.Internal.DefaultGrpcClientFactory.CreateClient[TClient](String name)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at ConsoleApp.Program.Main(String[] args)
```

**Comment by JamesNK** [comment] 2024-09-06 07:22
I think this works if you use gRPC 2.64.0 or later.

**Comment by iliar-turdushev** [comment] 2024-09-06 07:29
> I think this works if you use gRPC 2.64.0 or later. It would be great if you could update your grpc package versions to the latest and see whether this is still a problem.

Correct, we just wanted to have here steps how to reproduce the issue on net462.

**Comment by JamesNK** [comment] 2024-09-06 07:35
Ok. Just saying, I think you can close this issue. The problem was in grpc and it's been fixed there and released.

**Closed** 2024-09-06 14:11 UTC
Labels: work in progress :construction:, area-resilience, bug
