### ISSUE TITLE
The ChainedConfigurationProvider may return null value if the inline configuration value is empty string

### ISSUE THREAD

**Issue by iron9light** [dotnet/extensions#3162] opened 2020-04-07 14:38 UTC
### Describe the bug
The ChainedConfigurationProvider may return null value if the inline configuration value is empty string

### To Reproduce
```csharp
var config1 = new ConfigurationBuilder().AddInMemoryCollection(new Dictionary<string, string>
{
    { "x", string.Empty },
}).Build();
var x = config1["x"]; // return ""

var config2 = new ConfigurationBuilder().AddConfiguration(config1).Build();
var y = config2["x"]; // return null
```

### Expected behavior
`ChainedConfigurationProvider` should return the same value as inline configuration.

### Additional context
Please take a look at this line of code: https://github.com/dotnet/extensions/blob/7d9baaf617741d775578c8018729ac5b75734c69/src/Configuration/Config/src/ChainedConfigurationProvider.cs#L47

Why it's check null as well as empty string? I think it should only check null.

```
Microsoft.Extensions.Configuration version "3.1.3"

.NET Core SDK (reflecting any global.json):
 Version:   3.1.200
 Commit:    c5123d973b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.200\

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  3.1.200 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by anurse** [comment] 2020-05-06 22:58
This is very similar to https://github.com/dotnet/extensions/issues/1341 and https://github.com/dotnet/extensions/issues/3083 . The config system doesn't distinguish between `null` and `string.Empty`. Both value have the same semantics (the value is not present).

**Comment by anurse** [comment] 2020-05-07 20:22
Closing this as a duplicate of https://github.com/dotnet/extensions/issues/2690

**Closed by anurse** 2020-05-07 20:22 UTC
Labels: area-config
