### ISSUE TITLE
Add async Log to ILogger.

### ISSUE THREAD

**Issue by doogdeb** [dotnet/extensions#2154] opened 2019-08-07 14:57 UTC
It is a common scenario for a client to send it's log messages to a service bus queue to be processed by a worker role (fire and forget). This was never a problem with the old ServiceBus QueueClient because you could send a message synchronously. However, the new QueueClient does not have that option so you can only send asynchronously. This is not compatible with the Logger.Log which is synchronous, so you are forced to either do something like below, which is not really recommended, or you have to completely re-design your logger to possibly save to memory cache, then have a hosted service to read from memory async and then send to SB queue, which seems a tad overkill.

Task.Run(() => _queueClient.SendAsync(message)).GetAwaiter().GetResult()

Please add an async method for such scenarios listed above.

**Comment by WeihanLi** [comment] 2019-08-08 09:44
seemed duplicated with #2141

**Comment by anurse** [comment] 2020-01-30 19:34
Closing as duplicate of #2141

**Closed by anurse** 2020-01-30 19:34 UTC
Labels: area-logging
