### ISSUE TITLE
Microsoft.Extensions.TimeProvider.Testing net462 issue

### ISSUE THREAD

**Issue by mcenzato** [dotnet/extensions#5180] opened 2024-05-27 10:02 UTC
### Description

An unit test project targeting net framework 462 referencing the package Microsoft.Extensions.TimeProvider.Testing v8.5.0 raise a warning when compiled 
```
1>C:\Users\marco.cenzato\.nuget\packages\microsoft.extensions.timeprovider.testing\8.5.0\buildTransitive\net462\Microsoft.Extensions.TimeProvider.Testing.targets(5,5): warning : Microsoft.Extensions.TimeProvider.Testing 8.5.0 doesn't support net462 and has not been tested with it. Consider upgrading your TargetFramework to net6.0 or later. You may also set <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings> in the project file to ignore this warning and attempt to run in this unsupported configuration at your own risk.
```
In the official repository [https://www.nuget.org/packages/Microsoft.Extensions.TimeProvider.Testing](https://www.nuget.org/packages/Microsoft.Extensions.TimeProvider.Testing) the package claims to support net462

### Reproduction Steps

Create a new .csproj project file with this content
```
<Project Sdk="Microsoft.NET.Sdk">
 
  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
 
  <ItemGroup>
    <PackageReference Include="Microsoft.Bcl.TimeProvider" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" Version="8.5.0" />
        
    <PackageReference Include="coverlet.collector" Version="6.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.10.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.4.0" />
    <PackageReference Include="MSTest.TestFramework" Version="3.4.0" />
  </ItemGroup>
 
</Project>
```
Build with VS (I'm using VS 2022 (64-bit) Version 17.10.0 ).
In output/buil window the following waring is reported:
```
warning : Microsoft.Extensions.TimeProvider.Testing 8.5.0 doesn't support net462 and has not been tested with it. Consider upgrading your TargetFramework to net6.0 or later. You may also set <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings> in the project file to ignore this warning and attempt to run in this unsupported configuration at your own risk.
```

### Expected behavior

No warning expected as the package is declared to support net462

### Actual behavior

At build time a waring is araised:
```
warning : Microsoft.Extensions.TimeProvider.Testing 8.5.0 doesn't support net462 and has not been tested with it. Consider upgrading your TargetFramework to net6.0 or later. You may also set <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings> in the project file to ignore this warning and attempt to run in this unsupported configuration at your own risk.
```

**Comment by dariusclay** [comment] 2024-05-28 17:54
Duplicate of #5162

**Closed by dariusclay** 2024-05-28 17:54 UTC
Labels: untriaged, bug
