### ISSUE TITLE
Potential unreleased lock in RedisCache.ConnectAsync

### ISSUE THREAD

**Issue by AndreyBiryulin** [dotnet/extensions#2314] opened 2019-09-09 05:36 UTC
### Describe the bug
I don't know how to repro it, but while I was reading through RedisCache I saw this:
```
private async Task ConnectAsync(CancellationToken token = default(CancellationToken))
{
    token.ThrowIfCancellationRequested();
    await _connectionLock.WaitAsync(token);
    try
    {
         ...
    }
    finally
    {
          _connectionLock.Release();
    }
}
```

token cancellation might happen after _connectionLock is acquired, but before code enters into try, so code in finally to call .Release will never happen
In this case connection won't be established and can't be established by consecutive calls

### To Reproduce
I don't know how

### Expected behavior
Code should be safe

**Comment by davidfowl** [comment] 2019-09-14 05:37
> token cancellation might happen after _connectionLock is acquired, but before code enters into try, so code in finally to call .Release will never happen
In this case connection won't be established and can't be established by consecutive calls

There's no code between the WaitAsync and the try so I'm not sure what the problem is. Can you clarify?

**Comment by brandondahler** [comment] 2019-09-20 18:19
@AndreyBiryulin I think you're under the false assumption that `SemaphoreSlim.WaitAsync(CancellationToken)` is capable of both throwing the TaskCancelledException _and_ acquiring the lock.

The underlying implementation of SemaphoreSlim is such that it will only _either_ acquire the lock _or_ throw the TaskCancelledException.  Once the lock is atomically acquired, the cancellation token is effectively ignored.

**Comment by anurse** [comment] 2020-01-23 18:12
Closing as this doesn't appear to have any action on our side. @AndreyBiryulin feel free to re-open or open a new issue if you have a concrete repro that shows this could happen. Our understanding from how SemaphoreSlim.WaitAsync works is that it cannot.

**Closed by anurse** 2020-01-23 18:12 UTC
Labels: area-caching
