### ISSUE TITLE
Microsoft.Extensions.Hosting.WindowsServices.WindowsServiceHelpers.IsWindowsService() return false if run in docker container

### ISSUE THREAD

**Issue by NetGH** [dotnet/extensions#2982] opened 2020-02-15 20:40 UTC
1. Build a windows service by following https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-3.1&tabs=visual-studio
2. Publish the service into a docker container
3. Run the service  
    
Actual Result:
=================
[SC] StartService FAILED 1053:

The service did not respond to the start or control request in a timely fashion

Additional Info:
=================
After troubleshooting Microsoft.Extensions.Hosting.WindowsServices.WindowsServiceHelpers.IsWindowsService() always returns false.

**Comment by Tratcher** [comment] 2020-02-19 18:36
Duplicate of https://github.com/dotnet/extensions/issues/2778.

**Closed by Tratcher** 2020-02-19 18:36 UTC
Labels: area-hosting
