### ISSUE TITLE
override AddStandardResilienceHandler for a specific connection handler doesn't work

### ISSUE THREAD

**Issue by guru98** [dotnet/extensions#5443] opened 2024-09-24 11:21 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I try to override the settings of resilience and timeout for a specific http named client but always fail. i try using .ConfigurePrimaryHttpMessageHandler(() => new HttpClientHandler()); or AddStandardResilienceHandler but it never work.

### Expected Behavior

parameters should be overitten

### Anything else?

Aspire 8.2

**Comment by iliar-turdushev** [comment] 2024-09-24 16:37
@guru98 Could you, please, elaborate what you are trying to achieve? Also, please, take a look at the following issue https://github.com/dotnet/extensions/issues/4814. Is that the functionality you're looking for?

**Comment by JohnGalt1717** [comment] 2024-09-25 16:13
Basically I was looking for a way like the method that was just posted to clear out the standard rules and replace them. The use case for this is when talking to Llama.cpp or AI you need to change timeouts or you get big problems, and the standard resilience doesn't allow overriding.

I.e. what I think should be happening is if you set the Timeout somewhere, it should override the defaults. But it doesn't.

**Comment by iliar-turdushev** [comment] 2024-10-01 16:12
Closed as a duplicate of https://github.com/dotnet/extensions/issues/4814.

**Closed by iliar-turdushev** 2024-10-01 16:12 UTC
Labels: untriaged, area-resilience
