### ISSUE TITLE
How to use IMemoryCache to get all cache keys?

### ISSUE THREAD

**Issue by gainorloss** [dotnet/extensions#2570] opened 2019-10-29 08:36 UTC
### Describe the solution you'd like
Please give me a solution to get all keys in 'IMemoryCahce';

**Comment by Tratcher** [comment] 2019-10-29 19:48
That's not supported. Duplicate of https://github.com/aspnet/Caching/issues/422#issuecomment-425485770.

**Comment by anurse** [comment] 2020-01-23 18:07
Closing as duplicate.

**Closed by anurse** 2020-01-23 18:07 UTC
Labels: area-caching
