### ISSUE TITLE
ConfigurationBinder.Get enhancement

### ISSUE THREAD

**Issue by rolfik** [dotnet/extensions#1214] opened 2019-03-04 11:49 UTC
When I use [ConfigurationBinder_Get](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.configurationbinder.get?view=aspnetcore-2.2#Microsoft_Extensions_Configuration_ConfigurationBinder_Get__1_Microsoft_Extensions_Configuration_IConfiguration_) do get my options from a configuration section, it returns null (for my options class) when a configuration section does not exist (has no values) instead of new instance which would be more useful in my opinion.
When at least one configuration value of the section exists, it returns new options instance even though no configuration value is related to the concrete options class.
Because the options class can define its default property values, it would be more consistent behavior to always get the instance.

I use the options binder from .NET Framework 4.6.2 project.

Marek

**Comment by anurse** [comment] 2020-03-10 20:54
This seems intentional to me, in order to allow you to easily detect the absence of a config section as distinct from one with only default values set. It would also be a breaking change to change this behavior. Finally, it can be worked around by adding `?? new MyOptionsType()` to the expression to convert null values into a fresh instance with default values applied.

Closing as this is by design.

**Closed by anurse** 2020-03-10 20:54 UTC
Labels: area-config, enhancement, super-triage, triage: low
