### ISSUE TITLE
Frequent System.OperationCanceledException in RefreshAsync

### ISSUE THREAD

**Issue by krishnasingh1818** [dotnet/extensions#1899] opened 2019-06-27 21:45 UTC
### Describe the bug
Am seeing frequent logs for below error in appinsight only during getasync.  RefreshAsync method has code  await _cache.KeyExpireAsync(_instance + key, expr);  i feel this one is taking too much time to execute
```

   at System.Threading.CancellationToken.ThrowOperationCanceledException (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Extensions.Caching.Redis.RedisCache+<RefreshAsync>d__25.MoveNext (Microsoft.Extensions.Caching.Redis, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)

```
### To Reproduce
1. Using version    2.1.2  Microsoft.Extensions.Caching.Redis" 
2. Azure redis basic c0
3. .net core 2.1 webapi running in azure kubernetes service containers

### Expected behavior
frequent OperationCanceledException should not be logged. 

### Additional context
```
System.OperationCanceledException:
   at System.Threading.CancellationToken.ThrowOperationCanceledException (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Extensions.Caching.Redis.RedisCache+<RefreshAsync>d__25.MoveNext (Microsoft.Extensions.Caching.Redis, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Extensions.Caching.Redis.RedisCache+<GetAndRefreshAsync>d__20.MoveNext (Microsoft.Extensions.Caching.Redis, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Extensions.Caching.Redis.RedisCache+<GetAsync>d__12.MoveNext (Microsoft.Extensions.Caching.Redis, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Extensions.Caching.Distributed.DistributedCacheExtensions+<GetStringAsync>d__7.MoveNext (Microsoft.Extensions.Caching.Abstractions, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at My.Caching.NetCore2.MyCache+<GetAsync>d__13`1.MoveNext (My.Caching.NetCore2, Version=2.0.15.0, Culture=neutral, PublicKeyToken=null)

```

**Comment by anurse** [comment] 2019-07-23 22:20
Are you cancelling your the `CancellationToken` that's being provided? That would indeed trigger an `OperationCanceledException` like this and would be expected.

> await _cache.KeyExpireAsync(_instance + key, expr); i feel this one is taking too much time to execute

If that takes too long, you won't get an `OperationCanceledException`. By the time that code path is hit, the token is no longer observed.

Can you provide a runnable sample reproducing the problem you're seeing? I'm not sure I follow exactly what your concern is here.

**Comment by krishnasingh1818** [comment] 2019-07-30 21:33
`
 public async Task<T> GetAsync<T>(string key, int? timeoutMilliSeconds = null)
        {
            TrackCacheOp(CacheRead);
            T result = default(T);
            ValidateGetOrRemoveKey(key);
            string value = null;
            var start = DateTime.UtcNow;
            var timer = System.Diagnostics.Stopwatch.StartNew();
            bool success = false;
            try
            {
                var cts = new CancellationTokenSource();
                cts.CancelAfter(timeoutMilliSeconds != null ? timeoutMilliSeconds.Value : _defaultTimeoutInMilliSec);
                value = await _cache.GetStringAsync(key, cts.Token);
                success = true;
                CheckForCacheMiss(value);
            }
            catch (Exception ex)
            {
                _logger.LogError(0,ex,$"Could not get value for '{key}' from cache. Exception: {ex.Message}");
                success = false;
                TrackCacheError(CacheRead);
            }
            finally
            {
                timer.Stop();
                TrackCache($"Get {key}", start, timer.Elapsed, success);
            }

            if (!string.IsNullOrWhiteSpace(value))
            {
                result = JsonConvert.DeserializeObject<T>(value);
            }
            return result;
        }
`

**Comment by krishnasingh1818** [comment] 2019-08-02 17:08
we passing cancellation token cuz without that it was spending too much time to connect to redis and error logs where getting generated indicating that to many seconds it was waiting to connect.

**Comment by anurse** [comment] 2019-08-03 05:28
I guess I'm still not clear on which behavior is unexpected then. If you are having difficulty connecting to Redis, that would be the issue to look at, not the cancellation.

Are you able to confirm that the Redis server is accessible from your application? Network connectivity issues and delays would cause this kind of behavior. What specific error do you get when it times out **without** the cancellation token?

**Comment by krishnasingh1818** [comment] 2019-08-04 02:06
hi, this error i we get randomly even during no/low load times.  my api which lives in aks (useast2) with istio tries to connect to azure redis (us east2) basic instance.  i checked azure redis and it has no signs of being under load.
arround close to 7 to 8% of calls everyday fail to connect to azure redis due to this error.

**Comment by anurse** [comment] 2019-08-04 03:23
> i checked azure redis metrics and it has no signs of being overloaded and consumption of cpu/memory/connected client very low

Low usage doesn't guarantee that it's available. There could be intermittent network delays or issues. The fact that only 7-8% of calls fail with this error indicates pretty clearly to me that these are intermittent errors.

The [`RefreshAsync`](https://github.com/aspnet/Extensions/blob/5ccd94fe0822e2620193ce28a36938fe77106d97/src/Caching/StackExchangeRedis/src/RedisCache.cs#L367) API that is being cancelled does very little before calling straight out to Redis. Have you considered adding a check to your application that determines if Redis is available? You could correlate this data with these timeout errors and see if they correspond to a time when the connection between your AKS nodes were not able to reach Azure Redis.

Do you know what specific failures you get when you **do not** Cancel the token and instead just let it fail? That may provide a clearer indication of where the failure lies (in the Redis node, the network or the client code).

**Comment by tap-absg** [comment] 2019-08-22 16:58
> Have you considered adding a check to your application that determines if Redis is available?

What operation in https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.caching.stackexchangeredis.rediscache?view=aspnetcore-2.2 would I use to do this? Should I just request a different key to check that redis available, and then issue the query for the key I actually want?

- How does this avoid the 7-8% failures?
- Is there anything that can be done about the overhead this adds to successful calls?
- Would any of this be fixed by MS changing the NuGet package to depend on a current version of StackExchange.Redis, instead of StackExchange.Redis.StrongName 1.2.6?

**Comment by anurse** [comment] 2020-01-23 18:01
Catching up a bit, apologies for the delay. If this is no longer an issue for you, feel free to close it.

> * Would any of this be fixed by MS changing the NuGet package to depend on a current version of StackExchange.Redis, instead of StackExchange.Redis.StrongName 1.2.6?

We have done that, but in a new package (since the new version has breaking changes): [`Microsoft.Extensions.Caching.StackExchangeRedis`](https://www.nuget.org/packages/Microsoft.Extensions.Caching.StackExchangeRedis). That may help resolve the issue, but I don't know for sure. Note that since the package was added in .NET Core 2.2, which is end-of-life, only the 3.1 version of that new package is officially supported (and you should avoid mixing 2.x and 3.x .NET Core packages).

> Should I just request a different key to check that redis available, and then issue the query for the key I actually want?

My suggestion would be to use something like Health Checks (https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-3.1) to run a Redis command against the server itself, to verify that's it's up and running. If you track when the health check passes/fails in logs, etc. then you could possibly correlate the failures to when the health check fails and get confirmation that the issue is network availability.

In general, this sounds precisely like a network timeout, so I'm not sure there's action we can take here. The cancellation token is firing because the Redis operation times out, which isn't something we can control.

**Comment by anurse** [comment] 2020-01-23 18:13
Filed #2898 to track better timeout handling in general.

**Comment by anurse** [comment] 2020-01-30 20:02
Closing as we will have #2898 to handle timeouts better. If you identify that this isn't related to a network availability issue, please feel free to file a new bug.

**Closed by anurse** 2020-01-30 20:02 UTC
Labels: area-caching
