### ISSUE TITLE
No Execution/Publication options...

### ISSUE THREAD

**Issue by electricessence** [dotnet/extensions#698] opened 2018-11-30 16:26 UTC
https://github.com/aspnet/Caching/blob/master/src/Microsoft.Extensions.Caching.Abstractions/MemoryCacheExtensions.cs#L92-L122

Great work on this package.
I'm glad to see these extensions, but there should be an option to allow for synchronization.
If there's a potentially long running process, there needs to be assurance that downstream requests await a 'common' task avoid the optimistic concurrency being done here.

Here I actually wrap the factory call to ensure that whichever task is actually inserted into the cache is the one that is 'started'.
https://github.com/electricessence/Open.Caching/blob/master/Open.Caching/CachePolicyBase.cs#L83-L107

I think these methods incur no negative by 'selecting' which task to start if inserted.

Maybe I missed how this ends up being done elsewhere in the code, was also a bit confused about the entry.Dispose() call.  If it's doing as I mentioned above, then close this issue.

**Comment by anurse** [comment] 2020-03-12 20:23
Duplicate of https://github.com/dotnet/extensions/issues/708

**Closed by anurse** 2020-03-12 20:23 UTC
Labels: area-caching
