### ISSUE TITLE
Use .net8 APIs for metrics 

### ISSUE THREAD

**Issue by klauco** [dotnet/extensions#4215] opened 2023-07-25 17:05 UTC
We should update the codebase:
- move to using IMeterFactory
- remove `Meter<T>`

**Comment by xakep139** [comment] 2023-07-25 20:37
@klauco remove `Meter<T>`?

**Comment by klauco** [comment] 2023-07-26 08:04
yes, Meter<T>, without having that part in code section, the editor did not render <T>

**Comment by RussKie** [comment] 2023-08-18 00:41
Duplicate of #4049

**Closed by RussKie** 2023-08-18 00:41 UTC
Labels: area-telemetry
