### ISSUE TITLE
IOptionsMonitor in AKS

### ISSUE THREAD

**Issue by capcndt** [dotnet/extensions#1708] opened 2019-05-12 16:03 UTC
### Describe the bug
I setup a .net core Web API in Program.cs
configurationBuilder.AddJsonFile("secrets/appsettings/appsettings.Kubernetes.json", optional: true, reloadOnChange: **true**);

I add a change event in the startup.cs
monitor.OnChange(d => logger.LogInformation(" Service Configuration Reloaded"));

The app does not reload the configuration when running in AKS, terminal shows files changes as expected. When run in IIS express change works as expected.

### To Reproduce
1. Setup a web api using .net core 2.2
2. Inject a configuration
3. Add a on change monitor using IOptionsMonitor
4. Publish the app to AKS, mount a secret that represent the configuration in the path expected by the configuration object
5. Delete and recreate the secret. The file is change in POD but change event is not trigger.

### Expected behavior
Configuration is reload when changes occur in the file

**Comment by derhally** [comment] 2019-05-18 14:13
I see the same issue when a k8s secret is updated.  The changes are reflected in the mount OptionsMonitor.OnChange is not called.

I can reproduce the same issue when running in docker with an appsettings.json file on a volume mounted.    If I edit the file on the windows side, the IOptionsMontior.OnChange is not called.   If I edit the file inside the container, then the IOptionsMontior.OnChange is called.

Some info about the environments

Running in Kubernetes or Docker

Host (useful for support):
  Version: 2.1.11
  Commit:  d6a5616240

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by derhally** [comment] 2019-06-12 22:03
@Eilon Is there any indication whether this is a bug in .net or is this standard behavior ?   Is this the right repo to have this issue open in?

**Comment by Eilon** [comment] 2019-06-12 22:47
This is probably the right place to start the investigation. Tagging @ajcvickers @HaoK 

Just a guess: there might be some weird stuff with how K8s exposes file changes to listeners (stuff gets weird when it isn't a physical file system). This might end up being an underlying issue in .NET Core or even K8s.

**Comment by derhally** [comment] 2019-06-13 13:35
I deployed a container that uses FileSystemWatcher and IOptionsMonitor.   The Container mounts a configmap to /app/settings/config1.

The directory looks like 

```
drwxr-xr-x 2 root root 36 Jun 13 13:13 ..2019_06_13_13_27_15.487080772
lrwxrwxrwx 1 root root 31 Jun 13 13:13 ..data -> ..2019_06_13_13_27_15.487080772
lrwxrwxrwx 1 root root 29 Jun 13 13:11 appsettings.extra.json -> ..data/appsettings.extra.json
```

when the configmap is updated  the filewatcher receives the following events

```
2019-06-13T13:30:09.8783547+00:00 [INFO] [10] [TestService.Watcher] Created: '/app/settings/config1/..2019_06_13_13_30_09.454418899' {}
2019-06-13T13:30:09.8786514+00:00 [INFO] [10] [TestService.Watcher]  Change 'Changed' '/app/settings/config1/..2019_06_13_13_30_09.454418899' {}
2019-06-13T13:30:09.8794371+00:00 [INFO] [10] [TestService.Watcher] Created: '/app/settings/config1/..data_tmp' {}
2019-06-13T13:30:09.8796090+00:00 [INFO] [10] [TestService.Watcher] Renamed '/app/settings/config1/..data_tmp' to '/app/settings/config1/..data' {}
2019-06-13T13:30:09.8799386+00:00 [INFO] [10] [TestService.Watcher] Deleted '/app/settings/config1/..2019_06_13_13_27_15.487080772' {}
```


OptionsMontior calls OnChange.

My guess is the file monitoring code used by configuration does not detect the change because it is specifically looking for file change events on file not knowing it is a symbolic link.

**Comment by Eilon** [comment] 2019-06-13 16:05
Ah, symlinks make things even trickier with file watchers. I have very little personal knowledge in this area so I'm afraid there's not much more I can add.

**Comment by Sacode** [comment] 2019-12-23 17:05
Duplicate of #1175

**Comment by anurse** [comment] 2020-01-30 19:52
Closing as duplicate of #1175

**Closed by anurse** 2020-01-30 19:52 UTC
Labels: area-options
