### ISSUE TITLE
Microsoft.Extensions.Configuration.ConfigurationBinder is not working with System.Numerics.BigInteger

### ISSUE THREAD

**Issue by Manunich** [dotnet/extensions#2815] opened 2019-12-31 08:55 UTC
For example, you have Data model:
```
public class Data  {
    public BigInteger Number { get; set; }
}
```
And then you try to get IOptionsSnapshot<Data> in some controller - you always got {0} value instead of actual big integer configuration value.
I was debugging code and find out that `property.GetValue(instance)` in the `BindProperty `method returns null..

**Comment by andrefilipegsilva** [comment] 2020-01-23 00:00
Hey,

I tested with a simple POCO class containing a `BigInteger` and the `property.GetValue(instance)` method returns fine. 

As I see, the problem is in the retrieval of the `TypeConverter` associated with the `BigInteger` struct ([here](https://github.com/dotnet/extensions/blob/0cfad8ab095654482e0c4268169f80da09034cbd/src/Configuration/Config.Binder/src/ConfigurationBinder.cs#L507)), which returns a default `System.ComponentModel.TypeConverter` that cannot actually convert from `string` to `BigInteger`. Looking at the reference source, I didn't find any native subclass of `TypeConverter` that could convert `BigInteger` anywhere...

**Comment by anurse** [comment] 2020-05-07 20:01
I don't think this is something we can prioritize resolving in the config binder. As you noted we'd have to special case it since there's no native TypeConverter for `BigInteger` from `string`. The recommended approach for now would be to keep it a string and have a different property/method/etc. to load the value. You could do something like this, for example:


```csharp
public class Data {
	private string _number;
	private BigInteger _parsed;

	public string Number {
		get => _number;
		set {
			_number = value;
			_parsed = BigInteger.Parse(value);
		}
	}
}
```

**Closed by anurse** 2020-05-07 20:01 UTC
Labels: area-config, enhancement
