### ISSUE TITLE
Update HTTP in and HTTP out metrics and enrichment

### ISSUE THREAD

**Issue by JamesNK** [dotnet/extensions#4154] opened 2023-07-07 08:13 UTC
.NET 8 adds built-in counters for HTTP in and HTTP out. Update packages in dotnet/extensions to use built-in counters and apply enrichment to them.

Blocked on:
* https://github.com/dotnet/runtime/issues/86281 and https://github.com/dotnet/runtime/issues/86961 to be completed for HTTP out functionality.
* https://github.com/dotnet/runtime/issues/87914 for HttpClientFactory configure defaults functionality.

cc @joperezr

**Comment by joperezr** [comment] 2023-08-17 21:56
@JamesNK Is this a dupe of https://github.com/dotnet/extensions/issues/4215?

**Comment by joperezr** [comment] 2023-08-17 21:57
@xakep139 Is this one of the things that you were planning on doing?

**Comment by JamesNK** [comment] 2023-08-17 22:59
> @JamesNK Is this a dupe of #4215?

No.

**Comment by xakep139** [comment] 2023-08-17 23:36
> @xakep139 Is this one of the things that you were planning on doing?

All metering bits were removed as part of the #4214, so I guess we can close this isse.

**Closed** 2023-08-18 00:42 UTC
Labels: untriaged
