### ISSUE TITLE
Enum and Integer constructor parameter default values become corrupted while using ServiceProvider GetService method

### ISSUE THREAD

**Issue by hmacat** [dotnet/extensions#3197] opened 2020-04-22 08:30 UTC
Hello there. 
When using GetService method of ServiceProvider class for instantiating a class which has constructor parameters of enum and/or integer type with default values, provided default values become corrupted after a while. This issue causes dangerous bugs at runtime. The issue exists in Microsoft.Extensions.DependencyInjection package with versions 3.\*.\* There is no problem for 2.\*.\* versions.

### To Reproduce
1. Using version 3.1.3 of package Microsoft.Extensions.DependencyInjection
2. Run this code 

```     
    class Program
    {
        static void Main(string[] args)
        {
            var serviceCollection = new ServiceCollection();

            serviceCollection.AddTransient<ISampleClass, SampleClass>();

            var services = serviceCollection.BuildServiceProvider();

            for (int i = 0; i < 1000; i++)
            {
                var instance = services.GetService<ISampleClass>() as SampleClass;
                Console.WriteLine($"sample enum: {instance.SampleEnumProperty} sample integer: {instance.SampleIntProperty}");
            }

            Console.ReadKey();
        }
    }

    public class SampleClass : ISampleClass
    {
        public SampleEnum SampleEnumProperty { get; set; }
        public int SampleIntProperty { get; set; }

        public SampleClass(SampleEnum scopeType = SampleEnum.Default, int sampleIntValue = 0)
        {
            this.SampleEnumProperty = scopeType;
            this.SampleIntProperty = sampleIntValue;
        }
    }

    public interface ISampleClass
    {
        SampleEnum SampleEnumProperty { get; set; }
        int SampleIntProperty { get; set; }
    }

    public enum SampleEnum
    {
        Default,
        Other
    }

```
3. See error
After a number of correct instantiations, the values for enum and integer parameters become corrupted. Please check the screenshot.

### Screenshots
![image](https://user-images.githubusercontent.com/1427737/79958908-20df1480-848c-11ea-87f2-96eccfda1877.png)

**Comment by anurse** [comment] 2020-04-30 17:03
Seems like a duplicate of https://github.com/dotnet/extensions/issues/2431 . Going to close as a duplicate unless I'm misinterpreting something.

**Closed** 2020-05-01 18:01 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-dependencyinjection
