### ISSUE TITLE
Implement of Microsoft.Extensions.Caching.SqlServer

### ISSUE THREAD

**Issue by ForkBug** [dotnet/extensions#710] opened 2018-05-11 14:20 UTC
We are doing a test about sql server. But found Microsoft.Extensions.Caching.SqlServer doesn't work with In-memory oltp due to in memory oltp doesn't support  DateTimeOffset.

According to https://github.com/aspnet/Caching/pull/8 and https://github.com/aspnet/Caching/issues/6, 
it seems the implement doesn't follow the design?

**Comment by anurse** [comment] 2020-03-10 14:56
Duplicate of https://github.com/dotnet/extensions/issues/1894 (I know this one is from earlier, just doing clean-up and reducing duplication).

**Closed by anurse** 2020-03-10 14:56 UTC
Labels: Investigate, area-caching
