### ISSUE TITLE
FileConfigurationProvider的Load方法可能导致配置获取为null

### ISSUE THREAD

**Issue by sxi3265** [dotnet/extensions#983] opened 2019-01-22 08:53 UTC
### bug描述
多线程访问读取配置时，可能读取到空。
源代码https://github.com/aspnet/Extensions/blob/95577f5a1903e1781328136bf073b929184758b5/src/Configuration/Config.FileExtensions/src/FileConfigurationProvider.cs#L62
此处先将Data赋值为新的Dictionary对象后，才从文件中读取配置，在多线程访问时会导致配置读取不到的问题

### 重现步骤
按照以下步骤重现或访问[FileConfigurationProviderDemo](https://github.com/sxi3265/FileConfigurationProviderDemo)
1.创建一个JsonConfigurationProvider，启用ReloadOnChange
```csharp
            var source = new JsonConfigurationSource
            {
                FileProvider = new PhysicalFileProvider(Environment.CurrentDirectory),
                Path = "test.json",
                Optional = true,
                ReloadOnChange = true,
                ReloadDelay = 250,
            };
            var configurationProvider =new JsonConfigurationProvider(source);
            configurationProvider.Load();
```
2.创建一个线程修改配置文件（或修改配置文件的修改时间）,创建TestJson类，创建test.json文件
```csharp
            Task.Factory.StartNew(() =>
            {
                var path = Path.Combine(Environment.CurrentDirectory, "test.json");
                while (true)
                {
                    File.SetLastWriteTime(path, DateTime.Now);
                    //File.WriteAllText(path, JsonConvert.SerializeObject(new TestJson
                    //{
                    //    Key = Guid.NewGuid().ToString("N")
                    //}));
                }
            });
```
```csharp
public class TestJson
    {
        [JsonProperty("key")]
        public string Key { get; set; }
    }
```
```json
{
  "key": "value" 
}
```
3.创建一个线程读取配置
```csharp
            Task.Factory.StartNew(() =>
            {
                var hasValueCount = 0;
                var noValueCount = 0;
                for (var i = 0; i < 100000000; i++)
                {
                    configurationProvider.TryGet("key", out var value);
                    if (string.IsNullOrEmpty(value))
                    {
                        noValueCount++;
                    }
                    else
                    {
                        hasValueCount++;
                    }
                }
                Console.WriteLine($"Has Value:{hasValueCount},no Value:{noValueCount}");
            });
```

### 预期结果
能正常读取到配置

### 实际结果
```
Has Value:99276270,no Value:723730
```

### 运行环境
dotnet --info
```
.NET Core SDK（反映任何 global.json）:
 Version:   3.0.100-preview-009812
 Commit:    e3abf6e935

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview-009812\

Host (useful for support):
  Version: 3.0.0-preview-27122-01
  Commit:  00c5c8bc40

.NET Core SDKs installed:
  1.0.4 [C:\Program Files\dotnet\sdk]
  1.1.9 [C:\Program Files\dotnet\sdk]
  1.1.10 [C:\Program Files\dotnet\sdk]
  1.1.11 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.301 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.600-preview-009426 [C:\Program Files\dotnet\sdk]
  2.2.100 [C:\Program Files\dotnet\sdk]
  3.0.100-preview-009812 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview-18579-0056 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3-servicing-26724-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview-27122-01 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-alpha-27128-4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
项目文件
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.2</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="2.2.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="test.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
```

**Comment by sxi3265** [comment] 2019-02-12 07:22
> @sxi3265 It looks like you are having troubles with getting changes to appear when trying to use ReloadOnChange. But my efforts at translating what you're saying are failing. Any chance of translating to English for me?

You can view this example https://github.com/sxi3265/FileConfigurationProviderDemo

**Comment by anurse** [comment] 2020-03-10 18:50
So, if I'm understanding this correctly you are changing the last write time of the file frequently in the background (forcing a reload) and when you read the config in a tight loop, sometimes the results are corrupt (a key is missing). Is that correct?

**Comment by anurse** [comment] 2020-03-10 19:21
Looks like this is the same as https://github.com/dotnet/extensions/issues/1184. Closing as duplicate.

Duplicate of https://github.com/dotnet/extensions/issues/1184

**Closed by anurse** 2020-03-10 19:21 UTC
Labels: Investigate, area-config, super-triage, triage: need author feedback
