### ISSUE TITLE
Data redaction doesn't work with record class

### ISSUE THREAD

**Issue by IvoryFeng** [dotnet/extensions#5188] opened 2024-05-29 23:41 UTC
If I use a class, it has no issue. But if I change class to record, I'll get errors. See below.

Step 1: add a record class
    internal record User()
    {
        public int Id { get; set; }

        [NoDataClassification]
        public string? Email { get; set; }
    }

Step 2: add log method
    internal static partial class Logging
    {
        [LoggerMessage(6001, LogLevel.Information, "Logging User: {User}")]
        public static partial void LogUser(this ILogger logger, [LogProperties] User user);
    }

Errors:
![image](https://github.com/dotnet/extensions/assets/110053734/18968d34-bf9c-4ea7-a599-7484181db774)

Environment/configuration:
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Compliance.Redaction" Version="8.5.0" />
    <PackageReference Include="Microsoft.Extensions.Telemetry" Version="8.5.0" />
    <PackageReference Include="Microsoft.Extensions.Telemetry.Abstractions" Version="8.5.0" />
  </ItemGroup>

</Project>

**Comment by joperezr** [comment] 2024-05-30 17:30
Hey @IvoryFeng, thanks for logging the issue. I believe it is a dupe of https://github.com/dotnet/extensions/issues/4657 which already mentions the fact that record types don't work well with redaction. @xakep139 can you validate that it indeed is a dupe and if so we can probably close this one as such and track the work on that other one

**Comment by IvoryFeng** [comment] 2024-05-30 22:59
No, I don't think it's the same. I read that one before. You see record A is working for him, but not record B. It doesn't work for me at all.

**Comment by xakep139** [comment] 2024-05-31 09:19
I don't think it's a dupe, since it doesn't related to `IEnumerable`.
The current behavior is expected, because you added `user` parameter into the logging message template `"Logging User: {User}"`. That way, default record's `ToString()` method will leak this property.
@geeknoidm can you please clarify whether `NoDataClassificationAttribute` marks properties as non-sensitive?

**Comment by geeknoid** [comment] 2024-05-31 17:23
I can repro this, there is definitely a problem in the generator. I'll take a look.

**Closed** 2024-06-03 15:48 UTC
Labels: area-telemetry, bug
