### ISSUE TITLE
How to overwrite IOptions with multiple values?

### ISSUE THREAD

**Issue by shagilt** [dotnet/extensions#1533] opened 2019-04-23 00:46 UTC
This is my default settings.
**RetrySettings.Default.json**
```
  "RetrySettings": {
      //Http codes which can retry
      "RetriableErrors": [ 301,423,503,509 ]
    }
```

This is my settings class:
```
public class RetrySettings
    {
        /// <summary>
        /// Set of retriable error code.
        /// Retry will happen only for errors in this list
        /// </summary>
        public IList<int> RetriableErrors { get; set; } = new List<int>
        {
            301, 423, 503
        };
    }
```

Now, client wanted to remove 509 from RetriableErrors, so they have updated appsettings.json with below values:
**appsettings.json**
```
  "RetrySettings": {
      //Http codes which can retry
      "RetriableErrors": [ 301,423,503] //509 is removed
    }

```
After this, my RetrySettings.RetriableErrors list contains 7 values(4 values from default json file and 3 from appsettings.json). Ideally, I wanted to see content from only appsettings.json.
Am I doing something wrong here?

**Comment by shagilt** [comment] 2019-05-17 01:35
@JunTaoLuo Is this issue already fixed? I see a commit related to this issue

**Comment by JunTaoLuo** [comment] 2019-05-17 17:50
That was for a unrelated issue. The issue reference was broken due to moving this issue between repos. As far as I can tell there has not been movement/investigation into this issue.

**Comment by shagilt** [comment] 2019-05-17 23:24
Thanks. Any idea whom should i contact for this?

**Comment by poke** [comment] 2019-05-28 16:37
This is probably a duplicate of #789.

**Comment by anurse** [comment] 2020-01-23 21:53
Yep, looks like a duplicate to me as well. Closing this one as a duplicate.

The issue isn't specific to Options, it's that the config system is a little messy when it comes to managing lists of items and merging config layers.

**Closed by anurse** 2020-01-23 21:53 UTC
Labels: area-config
