### ISSUE TITLE
Microsoft.Extensions.Http.Resilience Breaks Application Insights Integration

### ISSUE THREAD

**Issue by phil000** [dotnet/extensions#5421] opened 2024-09-12 20:30 UTC
### Description

This may seem like an obscure one, but it's easily reproducible.

2 months ago we upgraded 2 solutions to Microsoft.Extensions.Http.Resilience 8.9.0. We didn't notice at the time but we have now noticed both projects have had all App Insights integration suppressed - all Traces, Requests and Dependencies stopped.

We have upgrade to Microsoft.Extensions.Http.Resilience 8.9.1 and the issue is reproducible in the local development environment.

NuGetSolver tool didn't really add much info.

### Reproduction Steps

Add Microsoft.Extensions.Http.Resilience 8.9.1 to solution. App insights integration is disabled.
Remove Microsoft.Extensions.Http.Resilience 8.9.0 from solution App insights integration is working again.

### Expected behavior

App insights integration is working

### Actual behavior

App insights integration is disabled

### Regression?

No

### Known Workarounds

Remove Microsoft.Extensions.Http.Resilience

### Configuration

.NET Core
  Version:      8.0.8
  Architecture: x64

**Comment by RussKie** [comment] 2024-09-12 23:23
> 2 months ago we upgraded 2 solutions to Microsoft.Extensions.Http.Resilience 8.9.0.

😲 8.9.0 was only released a week ago...

![image](https://github.com/user-attachments/assets/6f521ada-6e78-4e75-9d9f-fd0d8589dcd5)

**Comment by RussKie** [comment] 2024-09-12 23:25
Could you please provide a small stand-alone repro?

**Comment by phil000** [comment] 2024-09-12 23:30
Sorry the original upgrade was to "Microsoft.Extensions.Http.Resilience" Version="8.6.0"
That had a bug where synchronous methods oh HttpClient were not incorporated into retries so we waited for that fix.
We are now on version 8.9.1 and the issue persists.
I will see if I can provide a small web project that exhibits the issue.

**Comment by phil000** [comment] 2024-09-13 00:34
Can you provide an email address where I can send the repo?
It isn't something we can post publicly.

**Comment by RussKie** [comment] 2024-09-13 02:05
You can submit your repro sample via the VS Feedback (an icon on the top RHS in VS or via via https://developercommunity.visualstudio.com/dotnet directly). There you'll be able to attach a zip archive and all the necessary repro instructions. Once submitted, please link the issue here so we can route it to our team.

**Please note**, that we're not able to debug customer apps (unless you have a service agreement, in which case you need to speak with your CSR), that's why we ask for small standalone repros.

**Comment by phil000** [comment] 2024-09-13 02:31
The issue comes down to adding or removing this line, in a very minimal solution with only 3 NuGet package references.

With this **AddResilienceHandler()** all App Insights integration stops. Without it, the logging works as expected.

```
//TODO: Add or remove the 'AddResilienceHandler' call and it prevents App Insights integration from working.
bool wantAppInsightsWorking = false;
if (!wantAppInsightsWorking)
{
	builder.AddResilienceHandler(typeof(TClass).Name, builder =>
	{
		builder.AddRetry(new HttpRetryStrategyOptions
		{
			MaxRetryAttempts = 6,
			UseJitter = true,
			ShouldRetryAfterHeader = true,
			Delay = TimeSpan.FromMilliseconds(100),
			MaxDelay = TimeSpan.FromSeconds(10),
			BackoffType = DelayBackoffType.Exponential
		});
	});
}
```

```
<PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.22.0" />
<PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="8.9.1" />
<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
```

**Comment by phil000** [comment] 2024-09-13 03:03
Here's the minimalist repo.

Steps to Reproduce:

1. Add or remove the call to **AddResilienceHandler** found in WebsiteStartupBuilder.cs
2. Run the web app
3. Observe that App Insights logging is \ is not in the VS Output window - something like *"Application Insights Telemetry (unconfigured):"*
 
[Repo.Web.zip](https://github.com/user-attachments/files/16987906/Repo.Web.zip)

**Comment by RussKie** [comment] 2024-09-13 07:42
It looks like this call somehow affects the AI registrations:
https://github.com/dotnet/extensions/blob/39f5d27bf5503b42d8743d47d853aac973d12b49/src/Libraries/Microsoft.Extensions.Http.Resilience/Resilience/ResilienceHttpClientBuilderExtensions.Resilience.cs#L118

@martintmk @iliar-turdushev any thoughts?

**Comment by iliar-turdushev** [comment] 2024-09-13 07:57
@phil000 Thank you for reporting this. We'll investigate and get back to you.

**Comment by iliar-turdushev** [comment] 2024-09-13 14:50
The ticket is a duplicate of the following one https://github.com/dotnet/extensions/issues/5222. The issue is caused by AppInsights. Here is detailed explanation of the issue https://github.com/dotnet/extensions/issues/5222#issuecomment-2179395156.

To fix the issue you have to reorder registration of AppInsights and Http.Resilience, in particular, first register AppInsights, and then Http.Resilience. For example, in the sample you provided you need to use the following order:

```csharp
public void ConfigureServices(IServiceCollection services, IConfiguration configuration, bool isDevelopment)
{
    AddControllers(services);

    // First - AppInsights.
    AddTelemetry(services, isDevelopment);

    // Then - Http.Resilience and any other services that use Keyed Services feature of DI
    // https://learn.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-8.0#keyed-services.
    AddHttpClients(services);
}
```

@phil000 Please, confirm that the workaround works for you. If it does then we'll close the issue. Thank you.

**Comment by phil000** [comment] 2024-09-15 01:22
Confirming that reordering the dependency registration solves the issue for us.
We have added a unit test to check for the  presence of TelemetryClient in the collection after the service provider is built.
Please close the case.

**Comment by RussKie** [comment] 2024-09-15 23:17
The AI bug is here: https://github.com/microsoft/ApplicationInsights-dotnet/issues/2879

**Closed by RussKie** 2024-09-15 23:17 UTC
Labels: area-resilience, bug

**Comment by RussKie** [comment] 2024-09-15 23:18
Duplicate of #5222

**Comment by RussKie** [comment] 2024-09-15 23:20
@iliar-turdushev could you please update the [package's readme](https://github.com/dotnet/extensions/blob/main/src/Libraries/Microsoft.Extensions.Http.Resilience/README.md) with this known issue?

**Comment by iliar-turdushev** [comment] 2024-09-16 06:46
Sure, I will. Two customers already faced the issue.
