### ISSUE TITLE
Add support for “in-memory tables” in Microsoft.Extensions.Caching.SqlServer

### ISSUE THREAD

**Issue by epignosisx** [dotnet/extensions#1894] opened 2019-06-27 03:59 UTC
Currently, the Microsoft.Extensions.Caching.SqlServer library does not play well with SQL Server in-memory tables. The reason is that the data type DateTimeOffset is not supported by IM tables. 

The library would need to change to a different data type like DateTime2.

**Comment by xantari** [comment] 2020-02-25 14:35
@epignosisx I created a branch based off of the Microsoft.Extensions.Caching.SqlServer library that supports this: https://github.com/xantari/Microsoft.Extensions.Caching.SqlServerInMemory

**Comment by xantari** [comment] 2020-02-25 14:38
Related: https://github.com/dotnet/aspnetcore/issues/17640

**Comment by anurse** [comment] 2020-03-12 17:13
Duplicate of https://github.com/dotnet/extensions/issues/741

**Closed by anurse** 2020-03-12 17:13 UTC
Labels: area-caching, super-triage, triage: future
