### ISSUE TITLE
Adding a typed HTTP client twice, throws exception

### ISSUE THREAD

**Issue by leastprivilege** [dotnet/extensions#2077] opened 2019-07-24 12:00 UTC
**EDIT by @rynowak** - see below for shiproom template.
----

Calling

`services.AddHttpClient<SomeType>()`

more than once throws an exception in 3.0 preview 7 - this used to work in 2.x.

Is that the intended behavior?

**Comment by rynowak** [comment] 2019-07-24 17:22
This is intended to throw in 3.0 and the reason is that we've gotten lots and lots of bug reports where users would do things like this:

```
services.AddHttpClient<Foo.SomeType>().ConfigureSomething(...);
services.AddHttpClient<Bar.SomeType>().ConfigureSomethingElse(...);
```

These will result in all of the configuration being applied to a single *logical client* because http client factory uses named options based on the type name (not the fully-qualified type name).

It would be possible for us to make this work in the future if necessary. It's clear that how this actually works is different from what users believe. The change in 3.0 was made to make this problem clear when it occurs.

**Comment by leastprivilege** [comment] 2019-07-24 18:11
So what's the recommendation then - this pattern seems common:

* a services.AddXXX extensions methods adds a bunch of services plus some default (typed) http clients
* this returns a builder
* the builder has some helpers to override the standard http clients

This is at least how we did it in IdentityServer. I am open to changing that.

**Comment by leastprivilege** [comment] 2019-07-24 18:15
..oh and what's the reason to not use the fully qualified type name?

**Comment by rynowak** [comment] 2019-07-24 18:24
> 
> 
> So what's the recommendation then - this pattern seems common:
> 
>     * a services.AddXXX extensions methods adds a bunch of services plus some default (typed) http clients
> 
>     * this returns a builder
> 
>     * the builder has some helpers to override the standard http clients
> 
> 
> This is at least how we did it in IdentityServer. I am open to changing that.

This hasn't come up before so I don't have a ready-made solution for it. It makes sense.

**Comment by ImoutoChan** [comment] 2019-09-13 22:05
What is expected behaviour when I do something like this:

```
services.AddHttpClient<ISomeInterface, SomeType>();
services.AddHttpClient<ISomeInterface, OtherType>();
services.AddHttpClient<ISomeInterface, OneMoreType>();
```

and then consume them with `IEnumarable<ISomeInterface>` in some constructor? This scenario worked fine before 3.0.

I found workaround and made it work like this:

```
services.AddHttpClient<SomeType>();
services.AddHttpClient<OtherType>();
services.AddHttpClient<OneMoreType>();

services.AddTransient<ISomeInterface>(provider => provider.GetRequiredService<SomeType>());
services.AddTransient<ISomeInterface>(provider => provider.GetRequiredService<OtherType>());
services.AddTransient<ISomeInterface>(provider => provider.GetRequiredService<OneMoreType>());
```
But it looks ugly.

**Comment by Spaniol** [comment] 2019-10-17 14:31
> These will result in all of the configuration being applied to a single _logical client_ because http client factory uses named options based on the type name (not the fully-qualified type name).

But most of people used this in a proper way, for example we have a lot of different services which expose same API for metrics collection, we used single IMetricsClientApi interface implementation which was registered for each service available in catalog and that resolved in IEnumerable<IMetricsClientApi>, we don't needed to know about each new service and add different implementations for each. Now we can't migrate to 3.0, we need to figure out how to reimplement this now

**Comment by FelschR** [comment] 2019-11-19 16:10
I've encountered this issue in my integration tests using `MicroserviceFactory` where I'm overriding an existing HttpClient with one that's to be used during the tests.

**Comment by rynowak** [comment] 2019-11-24 22:31
#### Description

In 3.0 we added validation to HttpClient Factory's registration code path to prevent some common mistakes. This new validation code blocks some valid use cases that we didn't know about.

#### Customer Impact

Attempting to call `AddHttpClient<T>` twice with the same `T` throws an exception. This pattern is used when both library code and user code want to collaborate on configuration of a client type.
		
#### Regression?

Yes, this is a regression from 2.2
		
#### Risk

Low. This add special casing to our validation code path to allow more patterns. The impact of this is that cases that are explicitly blocked by an exception in 3.0 (but were allowed in 2.2) will be allowed again.

**Comment by photomoose** [comment] 2020-01-09 20:35
We've just stumbled into this issue after upgrading our projects from 2.2 to 3.1. In 2.2, we were relying on the ability to call `AddHttpClient<T>()` subsequent times, e.g. in `.ConfigureTestServices()` to override an `HttpClient`'s message handler in tests.

```
           var hostBuilder = new HostBuilder()
                .ConfigureWebHost(builder =>
                {
                    builder.UseTestServer()
                           .UseStartup<Startup>()
                           .ConfigureTestServices(services => 
                           {
                                 services.AddHttpClient<IIdentityServiceClient, IdentityServiceClient>()
                 .ConfigurePrimaryHttpMessageHandler(s => _testIdentityServer.CreateHandler());
                           });
                 });
```

**Closed** 2020-01-16 18:24 UTC
Labels: :heavy_check_mark: Resolution: Fixed, area-httpclientfactory, enhancement, servicing-consider
