### ISSUE TITLE
CommandLineConfigurationProvider isn't throwing an exception if providing argument which isn't there in switch

### ISSUE THREAD

**Issue by jaydeept** [dotnet/extensions#1284] opened 2019-03-20 11:16 UTC
I am using `CommandLineConfigurationProvider` for the command line arguments where I have observed that even though I am providing some random attribute as part of parameter `args` which isn't there in `switchMappings`, I am not getting an exception. 
I think exception should have been raised if argument doesn't exist in switch and also if no value has been provided for valid argument.

**Comment by anurse** [comment] 2020-03-10 20:51
This is the expected behavior. The switch mappings are not a list of all allowed, they are just mappings of alternate names to use so that you can use shorter names. It's still entirely reasonable to specify any configuration option via the command line, even if it's not pre-defined in the switch mappings.

It's also expected that a switch with no corresponding value **not** throw an exception. In general, we avoid throwing exceptions in this command-line parsing because the command-line config provider is not designed to be a general-purpose command line parser. When we encounter a switch with no missing value, we skip it entirely, presuming that it may still be relevant to some other command-line parsing logic.

Closing as this is all expected behavior and by-design.

**Closed by anurse** 2020-03-10 20:51 UTC
Labels: Investigate, area-config
