### ISSUE TITLE
The latest version of `Microsoft.Extensions.Diagnostics.Probes` is not `8.0.0`

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/extensions#4756] opened 2023-11-27 10:35 UTC
The latest version of `Microsoft.Extensions.Diagnostics.Probes` is not `8.0.0` while other packages like `Microsoft.Extensions.Diagnostics.Testing`/`Microsoft.Extensions.Diagnostics.ResourceMonitoring` etc is `8.0.0`, should it be `8.0.0`, is this an issue?

![image](https://github.com/dotnet/extensions/assets/7604648/fe426683-75cf-4b83-a264-ea6bea8bbc4e)

https://www.nuget.org/packages/Microsoft.Extensions.Diagnostics.Probes

**Comment by joperezr** [comment] 2023-11-27 17:42
Thanks for reaching out @WeihanLi, this is actually by design. This package is still in the "dev" stage meaning it's API is not yet finalized and is all marked as experimental. Due to this, we are not emitting a stable package yet. You can see that we set this package to remain in the dev stage here:

https://github.com/dotnet/extensions/blob/c8383902da237c8efd61a37808e444ac9b838f59/src/Libraries/Microsoft.Extensions.Diagnostics.Probes/Directory.Build.props#L2-L8

Once the API stabilizes in a future release, the package will start having stable versions as well.

**Comment by joperezr** [comment] 2023-11-27 17:45
I understand that this is also confusing as the package description/readme doesn't clearly state what stage this package is in, and that is due to a bug that is not currently rendering the README's correctly in NuGet.org: https://github.com/dotnet/extensions/issues/4722

Given this issue was mostly a question and I believed I answered it, I'm closing this issue for now. @WeihanLi please feel free to re-open if you think otherwise or have any follow-up questions.

**Closed by joperezr** 2023-11-27 17:45 UTC

**Comment by WeihanLi** [comment] 2023-11-30 01:26
Get it, thanks very much @joperezr
