### ISSUE TITLE
Benchmark projects fail when run

### ISSUE THREAD

**Issue by martincostello** [dotnet/extensions#2984] opened 2020-02-16 16:57 UTC
### Describe the bug

Assuming there isn't a special command somewhere that's required to _"make things work"_ that I've not found in the docs and not run, it appears that some of the benchmark projects in master are broken.

I was trying to add a new benchmark project for something I was playing around with locally, but I couldn't get it to work. I then tried to run an existing benchmark to check it was just something I'd broken in the new one I added but got the same result.

It appears that the benchmark projects are loading reference assemblies for the dependencies of their dependencies, rather than from the source, which then causes the benchmarks to fail at runtime.

```
Unhandled exception. System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (0x80131058)
Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (0x80131058)
Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (0x80131058)
Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (0x80131058)
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at BenchmarkDotNet.Extensions.ReflectionExtensions.GetRunnableBenchmarks(Assembly assembly)
   at BenchmarkDotNet.Running.BenchmarkSwitcher..ctor(Assembly assembly)
   at Microsoft.AspNetCore.BenchmarkDotNet.Runner.Program.Main(String[] args) in C:\Coding\dotnet\Extensions\src\Shared\src\BenchmarkRunner\Program.cs:line 27
System.BadImageFormatException: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (0x80131058)
File name: 'Microsoft.Extensions.Logging.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' ---> System.BadImageFormatException: Cannot load a reference assembly for execution.
System.BadImageFormatException: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (0x80131058)
File name: 'Microsoft.Extensions.Logging.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' ---> System.BadImageFormatException: Cannot load a reference assembly for execution.
System.BadImageFormatException: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (0x80131058)
File name: 'Microsoft.Extensions.Logging.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' ---> System.BadImageFormatException: Cannot load a reference assembly for execution.
System.BadImageFormatException: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (0x80131058)
File name: 'Microsoft.Extensions.Logging.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' ---> System.BadImageFormatException: Cannot load a reference assembly for execution.
```

There was one example of a benchmark project I found that tests a project that has no references to other projects' source in the repository, `Microsoft.Extensions.Primitives.Performance`, and those run as expected.

I tried manually adding all the dependencies of the project chain to the `csproj` as a workaround, but that didn't seem to work either. That seemed to duplicate references (based on the output for `dotnet restore`) so that it added ref and src versions for the projects, and didn't resolve the runtime problem anyway.

### To Reproduce

1. `restore.cmd`
1. `build.cmd`
1. `. .\activate.ps1`
1. `cd .\src\Logging\Logging\perf\`
1. `dotnet run -c Release`

### Expected behavior

Benchmark runs and displays results.

### Additional context
Output of `dotnet --info`

```
(Extensions) PS C:\Coding\dotnet\Extensions\src\Primitives\perf> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   5.0.100-preview.1.20106.1
 Commit:    9cc3298e79

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Coding\dotnet\Extensions\.dotnet\sdk\5.0.100-preview.1.20106.1\

Host (useful for support):
  Version: 5.0.0-preview.1.20115.9
  Commit:  24967d0491

.NET Core SDKs installed:
  5.0.100-preview.1.20106.1 [C:\Coding\dotnet\Extensions\.dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 5.0.0-alpha.1.20071.6 [C:\Coding\dotnet\Extensions\.dotnet\shared\Microsoft.AspNetCore.App]   Microsoft.NETCore.App 5.0.0-alpha.1.20103.10 [C:\Coding\dotnet\Extensions\.dotnet\shared\Microsoft.NETCore.App]        Microsoft.NETCore.App 5.0.0-preview.1.20115.9 [C:\Coding\dotnet\Extensions\.dotnet\shared\Microsoft.NETCore.App]       Microsoft.WindowsDesktop.App 5.0.0-preview.1.20105.7 [C:\Coding\dotnet\Extensions\.dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by Pilchie** [comment] 2020-02-18 17:23
@sebros or @davidfowl any ideas here?

**Comment by Pilchie** [comment] 2020-02-21 16:47
Adding @dotnet/aspnet-build too. I thought someone looked at these recently.

**Comment by dougbu** [comment] 2020-02-25 06:01
This is probably a point-in-time issue caused by merging incomplete ref/ assembly changes from the 'release/3.1' branch. That infrastructure remains in flux in 'master'.

I suggest trying with the following in the projects that are failing
``` msbuild
<CompileUsingReferenceAssemblies>false</CompileUsingReferenceAssemblies>
```
If this works, would be great to fix 'master' before we get ref/ assemblies sorted. Might be a candidate for the `good first issue` label 😺

**Comment by martincostello** [comment] 2020-02-25 09:57
Thanks @dougbu - I'll try that out with what I was experimenting with locally that lead to this some time this week and see if it resolves the problem.

**Comment by martincostello** [comment] 2020-03-07 13:49
I tried using `CompileUsingReferenceAssemblies` but it didn't seem to help, at least not to the extent of going down the rabbit hole of how many dependencies and project files I tried to change that didn't fix the problem.

**Comment by dennymao** [comment] 2020-03-09 18:12
Mark
I also encountered the same problem.

**Comment by dennymao** [comment] 2020-03-09 19:04
### On windows  ()
make a new folder
git clone https://github.com/dotnet/extensions.git  [ps:default branch is master]
.\restore.cmd
.\build.cmd
. .\activate.ps1
.\artifacts\bin\GenericHostSample\Debug\netcoreapp5.0\GenericHostSample.exe

Response:```
Unhandled exception. System.BadImageFormatException: Could not load file or assembly 'Microsoft.Extensions.Hosting.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (0x80131058)
File name: 'Microsoft.Extensions.Hosting.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' ---> System.BadImageFormatException: Cannot load a reference assembly for execution.
   at GenericHostSample.WindowsServiceControlled.Main(String[] args)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at GenericHostSample.WindowsServiceControlled.Main(String[] args)
   at GenericHostSample.WindowsServiceControlled.<Main>(String[] args)
```

### on linux (ubuntu-1804)
./build.sh
source activate.sh
dotnet ./artifacts/bin/GenericHostSample/Debug/netcoreapp5.0/GenericHostSample.dll
Response:```
Unhandled exception. System.BadImageFormatException: Could not load file or assembly 'Microsoft.Extensions.Hosting.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (0x80131058)
File name: 'Microsoft.Extensions.Hosting.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' ---> System.BadImageFormatException: Cannot load a reference assembly for execution.
   at GenericHostSample.WindowsServiceControlled.Main(String[] args)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at GenericHostSample.WindowsServiceControlled.Main(String[] args)
   at GenericHostSample.WindowsServiceControlled.<Main>(String[] args)
Aborted (core dumped)

```

I tried to get many different versions.

https://codeload.github.com/dotnet/extensions/zip/v3.0.0  <--> Tested to work
https://codeload.github.com/dotnet/extensions/zip/v2.1.10 <--> Tested to work

So. 
For these sample programs,Is there a problem with the late branch:(master) .....

**Comment by anurse** [comment] 2020-05-07 22:38
After the restructuring, most of these moved to dotnet/runtime and there's other infrastructure there. I'm going to close this but please feel free to open new issues in dotnet/runtime to track making benchmarks in that repo runnable.

**Closed by anurse** 2020-05-07 22:38 UTC
Labels: area-infrastructure
