### ISSUE TITLE
Unable to add resilience handler from service or registry

### ISSUE THREAD

**Issue by glen-84** [dotnet/extensions#4666] opened 2023-11-03 11:09 UTC
1. There is no `AddResilienceHandler("PipelineKey")` to add a handler from the service collection.
2. There is no `AddResilienceHandlerFromRegistry("PipelineKey")` to add a handler from the pipeline registry.

**Comment by geeknoid** [comment] 2024-01-24 19:33
Closing as a dupe of #4893

**Closed by geeknoid** 2024-01-24 19:33 UTC
Labels: area-resilience, enhancement
