### ISSUE TITLE
Sensitive records aren't redacted when used in IEnumerable<T> in a logging method

### ISSUE THREAD

**Issue by xakep139** [dotnet/extensions#4657] opened 2023-11-02 17:41 UTC
### Description

The source-generated implementation of `M1` (see reproduction steps) won't redact or report an error and will emit sensitive data as-is.

### Reproduction Steps

Consider this example:

```cs
[AttributeUsage(AttributeTargets.Property | AttributeTargets.Parameter)]
internal sealed class PrivateDataAttribute : DataClassificationAttribute
{
    public static DataClassification Classification => new("ComplianceTaxonomy", "ContosoClassification");

    public PrivateDataAttribute() : base(Classification)
    {
    }
}

record A([property: PrivateData] string SensitiveProperty);

record B(IEnumerable<A> collection);

internal static partial class Log
{
    [LoggerMessage(LogLevel.Information, "Something...")]
    static partial void M1(ILogger logger, [LogProperties] B param);
}
```

Then create an `ILogger` and call the method:
```cs
using var loggerFactory =
    LoggerFactory.Create(builder =>
    {
        builder.EnableRedaction();
        builder.AddJsonConsole();
        builder.Services.AddRedaction(x => x.SetRedactor<ErasingRedactor>(new DataClassificationSet(PrivateDataAttribute.Classification)));
    });

var logger = loggerFactory.CreateLogger("MyDemoLogger");

Log.M1(logger, new B([new A("Sensitive value here!")]));
```

### Expected behavior

An error emitted by the source-gen or redaction happenned.

### Actual behavior

The current implementation emits `"param.collection": "[\u0022A { SensitiveProperty = Sensitive value here! }\u0022]"` with a JSON console exporter.

**Comment by geeknoid** [comment] 2023-11-02 17:50
This is by design.

The intent here is that redaction will occur on the final string. not on the individual items in the enumeration. That is, we do Redact(Stringify(Enumerable)) and not Stringify(IEnumerable(Redact)) if you get what I mean.

So you need to apply a data classification on the log method parameter and that will be redacted.

**Comment by joperezr** [comment] 2023-11-06 17:36
Just to make sure I'm following, this wasn't really fixed by https://github.com/dotnet/extensions/pull/4658 but instead that PR just started to make it so we don't silently fail and throw an error, but in the end the real fix should be in Roslyn, correct?

**Comment by xakep139** [comment] 2023-11-08 07:29
This wasn't affected by #4658 at all. The logic there doesn't check `IEnumerable`

**Comment by geeknoid** [comment] 2024-05-31 18:38
I'm closing this as by-design. There is an easy procedure to get this working, mentioned above.

**Closed by geeknoid** 2024-05-31 18:38 UTC
Labels: area-telemetry, enhancement
