### ISSUE TITLE
Constructor resolution for HttpClientFactory is more restrictive than ServiceCollection.

### ISSUE THREAD

**Issue by veleek** [dotnet/extensions#3132] opened 2020-03-31 18:43 UTC
### Describe the bug
A type registered in the ServiceCollection will dynamically select the best constructor using all of the types available.  So if you have a class with two constructors:

```
public MyClient(HttpClient foo) ...

public MyClient(HttpClient foo, MyClientConfig config)...
```

It will pick the second constructor if `MyClientConfig` is registered, and fall back to the first if only `HttpClient` is registered.

Switching over to using `.AddHttpClient<MyClient>()` starts failing with the error message that multiple constructors match:

```
Multiple constructors accepting all given argument types have been found in type 'MyClient'. There should only be one applicable constructor.
```

### To Reproduce
1. Using version '3.1.3' of package 'Microsoft.Extensions.Http'
2. Run this code in LinqPad
```
void Main()
{
	IServiceCollection serviceCollection = new ServiceCollection();
	serviceCollection.AddSingleton(new MyClientConfig { });
	serviceCollection.AddHttpClient<MyClient>();
	
	var services = serviceCollection.BuildServiceProvider();
	services.GetRequiredService<MyClient>();
}

public class MyClient
{
	public MyClient(HttpClient client)
	{
		"Client Const".Dump();
	}
	
	public MyClient(HttpClient client, MyClientConfig config)
	{
		"Client+Conf Const".Dump();
	}
}

public class MyClientConfig { }
```

3. See error: `Multiple constructors accepting all given argument types have been found in type 'MyClient'. There should only be one applicable constructor.`

### Expected behavior
The resolution logic for HttpClients should mirror the resolution logic for regular services.  It should pick the constructor with the most parameters that it has the values available for.

**Comment by rynowak** [comment] 2020-03-31 19:49
Unfortunately, for [various technical reasons](https://github.com/dotnet/extensions/issues/1806#issuecomment-500055231), it isn't really feasible for us to make this "just work". The functionality that's used to instantiate something when it's registered in DI vs when it's not have different requirements. 

The behavior of HttpClient Factory is based on [`ActivatorUtilities`](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-3.1#constructor-injection-behavior).

There's a few options for you can work around this:

- If you know statically that you always want a specific constuctor to match, then apply [`ActivatorUtilitiesConstructorAttribute`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.activatorutilitiesconstructorattribute?view=dotnet-plat-ext-3.1&viewFallbackFrom=aspnetcore-2.2) and we'll always use that one.
- If you need the selection of a constructor to be dynamic based on what's in DI, then I'd suggest passing in a factory function and deciding yourself what constructor to call. Factory functions get access to the `IServiceProvider` so you can look for any services you want.

**Comment by veleek** [comment] 2020-04-01 00:36
@rynowak - Thanks for the description.  I figured it would be something like that.  

Unfortunately, when using `services.AddHttpClient<MyClient>(...)` there isn't an override that allows you to construct the `MyClient` instance yourself.  You have access to the `IServiceProvider` to override the configuration on the HttpClient that gets passed to the underlying, but not to override the actual construction of the client object.  

In order to get the required behavior you need to both manually register and configure a non-typed (maybe named) HttpClient with all of the additional handlers and then separately register your typed client class with a factory function so that you can request the correct HttpClient instance from the factory.  Something along the lines of:

```csharp
services.AddHttpClient("MyClient")
  .AddRetryPolicies(...)
  .AddOtherPolicies(...)

services.AddTransient<MyClient>(serviceProvider => 
{
  IHttpClientFactory factory = getFactory...;
  return new MyClient(factory.GetClient("MyClient", getConfig));
}
```

Totally doable, but definitely seems like overkill.  

The specific comment you referred to actually says

> Instead, we take the "provided" arguments (the ones passed directly in to ActivatorUtilities.CreateInstance) and just find the longest constructor that can accept those. Then the remaining arguments are expected to be present.

And while it's not specifically the behavior I'm looking for, it would have actually worked in this case, but we're not seeing that behavior and getting an exception instead.  Should that behavior be changed?  

In either result, the IHttpClientFactory documentation should be updated to indicate that.  I'm going to submit a PR to update [this page](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-3.1&source=docs#typed-clients) to provide a bit more detail around constructors for typed clients unless you think there's a possibility of this behavior changing anytime soon.

**Comment by rynowak** [comment] 2020-04-01 23:40
> Unfortunately, when using services.AddHttpClient<MyClient>(...) there isn't an override that allows you to construct the MyClient instance yourself.

You have to do `services.AddHttpClient("name").AddTypedClient<MyClient>(...)`. [This one](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.httpclientbuilderextensions.addtypedclient?view=dotnet-plat-ext-3.1#Microsoft_Extensions_DependencyInjection_HttpClientBuilderExtensions_AddTypedClient__1_Microsoft_Extensions_DependencyInjection_IHttpClientBuilder_System_Func_System_Net_Http_HttpClient_System_IServiceProvider___0___) We added some overloads of `AddHttpClient` in 5.0 that make this functionality easier to find. 

----

> And while it's not specifically the behavior I'm looking for, it would have actually worked in this case, but we're not seeing that behavior and getting an exception instead

I think that comment is leaving out a detail - when considering longest.. it's only the parameters that match the provided arguments that are considered. It does not consider whether or not `MyClientConfig` is provided when making a decision. 

I think a better description would be:

> Instead, we take the "provided" arguments (the ones passed directly in to ActivatorUtilities.CreateInstance) and just find the constructor that accepts *the most* of those. If multiple constructors can accept the provided arguments, it's considered ambiguous. Then the remaining arguments are expected to be present.

Since both of these constructors match `HttpClient` (provided) then they are considered ambiguous. In order to do what you want (different behavior based on what services are registered in DI) then the algorithm would have to consider what's in DI, and it specifically does not do that.

It's unlikely that we'd change this behavior because the impact of changing fundamental things like `ActivatorUtilities` would be huge and unpredictable. It's use for **lots** of stuff.

If you're willing, please submit a PR to the doc that clarifies this, I'm happy to help review and make suggestions.

**Comment by veleek** [comment] 2020-04-01 23:56
Thanks for the clarifications!  I was not aware of `AddTypedClient<...>`, but yes, that would make this process a bit easier.

Understood about the ambiguous constructor matching.  I see now that `AddTypedClient` is referenced in the **Generated clients** section of that documentation page.  I'll see if I can come up with a clear way to point that out.

**Comment by anurse** [comment] 2020-05-07 22:02
Closing as it sounds (from above conversations and labelling) that this behavior is by design. Let me know if I'm misinterpreting the thread!

**Closed by anurse** 2020-05-07 22:02 UTC
Labels: :heavy_check_mark: Resolution: By Design, area-httpclientfactory, enhancement
