### ISSUE TITLE
GetValue wants to be able to pass

### ISSUE THREAD

**Issue by JHeLiu** [dotnet/extensions#1362] opened 2019-04-07 02:58 UTC
```
 var config = new Microsoft.Extensions.Configuration.ConfigurationBuilder()
                 // .SetBasePath(System.IO.Directory.GetCurrentDirectory())
                 .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
                 .Build();
            //Gets the correct value
            var value1 = config.GetSection("user:info").Get<List<User>>();

            //The value obtained is null
            var value = config.GetValue<List<User>>("user:info");
            Console.WriteLine(value1);
            Console.WriteLine(value);
```

Can I make GetValue generic?  maybe my json has object object array string, whatever,
Of course I don't know what the author's design is, but I'm thinking that if a developer USES his profile, he should know exactly what data types are in the profile.Give me a little help with the explanation。
Or there is a better way to get, if not trouble can help me, thank you

**Comment by anurse** [comment] 2020-03-11 21:22
This is basically the expected behavior, though I agree it might be a little counter-intuitive. If `user:info` is a list of items, then what the config system sees is the key-value pairs below (I'm just making up the `foo` and `bar` sub-keys since you didn't provide the specific layout of your `User` class):

```
user:info:0:foo = "a"
user:info:0:bar = "a"
user:info:1:foo = "b"
user:info:1:bar = "b"
user:info:2:foo = "c"
user:info:2:bar = "c"
```

Calling `GetSection` gets a collection of all keys with the specified prefix. However, calling `GetValue` gets **just the value with the specified name**. There isn't actually a key named `user:info` in your set, so it returns `null`.

Closing as this is the expected behavior.

**Closed by anurse** 2020-03-11 21:22 UTC
Labels: Investigate, area-config
