### ISSUE TITLE
Request for ConsoleLogger implementation to have configurable logging level strings

### ISSUE THREAD

**Issue by dnealy** [dotnet/extensions#946] opened 2019-01-15 12:30 UTC
We're using LogDNA to capture logs from our services, and their default log ingestion/parsing rules don't understand some of the hard coded strings found in:

```
   private static string GetLogLevelString(LogLevel logLevel)
        {
            switch (logLevel)
            {
                case LogLevel.Trace:
                    return "trce";
                case LogLevel.Debug:
                    return "dbug";
                case LogLevel.Information:
                    return "info";
                case LogLevel.Warning:
                    return "warn";
                case LogLevel.Error:
                    return "fail";
                case LogLevel.Critical:
                    return "crit";
                default:
                    throw new ArgumentOutOfRangeException(nameof(logLevel));
            }
        }
```

`fail` for Error seems particularly non-standard, and `dbug` is probably our biggest offender for running up our LogDNA bill.  I've worked around the problem at the moment by implementing a custom logger, but this seems like something that could be done much better in the Core framework.

My request is that you guys provide some configuration ability around these strings, rather than just using these hard-coded, non-standard strings.

**Comment by chrislalos2** [comment] 2019-01-17 17:40
This is bothersome to me as well. I can understand this being an option, but I can't understand it being the default, let alone hardwired behavior.

I'm genuinely wondering, what were people thinking?

**Comment by anurse** [comment] 2020-03-12 20:58
We're likely going to resolve this as part of #2479 , which will include custom formatting APIs that could handle this. I'm going to mark this as a duplicate of that.

Duplicate of #2479

**Closed by anurse** 2020-03-12 20:58 UTC
Labels: area-logging
