### ISSUE TITLE
MemoryCacheExtensions: Don't await on factory to avoid multiple invocations

### ISSUE THREAD

**Issue by ackava** [dotnet/extensions#1242] opened 2019-03-13 04:08 UTC
File: https://github.com/aspnet/Extensions/blob/master/src/Caching/Abstractions/src/MemoryCacheExtensions.cs

```c#
        public static async Task<TItem> GetOrCreateAsync<TItem>(this IMemoryCache cache, object key, Func<ICacheEntry, Task<TItem>> factory)
        {
            if (!cache.TryGetValue(key, out object result))
            {
                var entry = cache.CreateEntry(key);
                result = await factory(entry);
                entry.SetValue(result);
                // need to manually call dispose instead of having a using
                // in case the factory passed in throws, in which case we
                // do not want to add the entry to the cache
                entry.Dispose();
            }

            return (TItem)result;
        }
```

This method will await till result is available, leading to multiple requests for same cache key..

```c#
    // lets assume that FetchFromUrl is an http request which takes couple of seconds to finish
    cache.GetOrCreateAsync("a", e => FetchFromUrl(e.Key));
    cache.GetOrCreateAsync("a", e => FetchFromUrl(e.Key));
```

Second call to `GetOrCreateAsync` will still create a new http request while even previous request for same key is in processing.

Changing `GetOrCreateAsync` to following will improve performance as all subsequent calls will not be queued, and first task will be awaited for all simultaneous requests.

```c#
        public static async Task<TItem> GetOrCreateAsync<TItem>(this IMemoryCache cache, object key, Func<ICacheEntry, Task<TItem>> factory)
        {
            if (!cache.TryGetValue(key, out object result))
            {
                var entry = cache.CreateEntry(key);
                result = factory(entry);
                entry.SetValue(result);
                // need to manually call dispose instead of having a using
                // in case the factory passed in throws, in which case we
                // do not want to add the entry to the cache
                entry.Dispose();
            }

            var r = result as Task<TItem>;

            try {
                return await r; 
            } catch {
                // this is to ensure that we remove
                // errornous Task<TItem> so subsequent calls 
                // for same key will create a new request
                cache.Remove(key);
                throw;
            } 
        }
```

The only drawback is all simultaneous calls for same key will fail if network error occurs for first request, but after error, cache is cleared for the same key and new requests will continue to work if underlying task is successful.

**Comment by brandondahler** [comment] 2019-03-15 17:20
I don't think you realize that your suggested code is fundamentally changing what is stored by the `CacheItem` in its `Value` property -- before it would store a value of type TItem, while your code would be storing a value of type Task<TItem>.

The general problem you are referring to also exists in other concurrent classes, such as `ConcurrentDictionary<TKey, TValue>` and they handle this issue in the same way that the current code handles this -- if there are multiple simultaneous calls, the factory can be called multiple times and ultimately the last one to provide the value is the one that is stored after all calls finish.

I think the problem is not properly solved on the library side, but instead on the caller's side.  There are two ways you can solve it, and you inadvertently provided one of the solutions:

1. Store/use Task<T> in the memory cache -- your factory method will produce a Task<T> almost instantaneously and have a much lower chance of simultaneity (technically still existent).   You will need to update all code that fetches the value from the cache to `await` the resulting value from the cache, but a given Task instance can be awaited multiple times with safety.  The only negative to this is that a Task that results in an exception will throw that exception each time it is awaited.

2. Wrap the underlying cache and manually define and use a locking system that creates key-specific locks in a thread-safe manner, locks said lock, re-checks that the value isn't in the cache, runs the factory method and stores the value if it still isn't there, releases the key-specific lock, and finally releases all references to the key-specific lock.  I've personally done this for a few different projects using a ConcurrentDictionary<TKey, SemaphoreSlim>, using `.GetOrAdd(key, () => new SemaphoreSlim(1))` to get/create the current key's lock and `.TryRemove(key)` at the end to release the references to the key-specific lock.

**Comment by ackava** [comment] 2019-03-18 15:58
@brandondahler 

My implementation was abstract, and yes I do know about `ConcurrentDictionary`, that's why this is a feature request and not a pull request, I know underlying storage will require some sort of changes as well.

> The only negative to this is that a Task that results in an exception will throw that exception each time it is awaited
This is not an issue as if there is a network issue, all awaiting tasks will fail anyway as all of them will face network issue, if there is a logical issue, all awaiting tasks will fail as well. My problem was too many simultaneous requests were causing some requests to fail and some to succeed.

I am using my own `ConcurrentDictionary` to achieve same with lock.

**Comment by anurse** [comment] 2020-03-12 17:39
Duplicate of https://github.com/dotnet/extensions/issues/708

**Closed by anurse** 2020-03-12 17:39 UTC
Labels: area-caching
