### ISSUE TITLE
IOptionsSnapshot does not provide newest value when running in docker environment

### ISSUE THREAD

**Issue by jehof** [dotnet/extensions#458] opened 2018-08-24 18:07 UTC
Hey there,
I wanted to implement what is described [here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-2.1#reload-configuration-data-with-ioptionssnapshot), but it seems to me that this is not working as intended.

I have setup a new asp.net core project (2.1.3) with docker-support (Linux container) in Visual Studio 2017 15.8.1 to demonstrate that.

Running the project using the Docker profile, the ValuesController will always return the old value, even when I change the appsettings during runtime.

Running the project using IIS Express profile, the ValuesController returns the changed value, from the appsettings.

I have read that we should set DOTNET_USE_POLLING_FILE_WATCHER to 1 or true, when running in a docker environment to watch for [changes](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/file-providers?view=aspnetcore-2.1#watch-for-changes), but even this does not help. also VS does this automatically, when debugging.

![image](https://user-images.githubusercontent.com/1583129/44600403-7657af80-a7d9-11e8-827e-d51f859faab6.png)

I have checked when running with Docker profile, what the PhysicalFilesProvider looks like and its set to _pollForChanges=true

![image](https://user-images.githubusercontent.com/1583129/44600287-1e20ad80-a7d9-11e8-92a7-91262dae9e5e.png)

So I´m stuck and I am running out of options. How to use this feature? We want to change some configurations of our services during runtime without restarting them.

[WebApplication12.zip](https://github.com/aspnet/Home/files/2319296/WebApplication12.zip)

**Comment by ajcvickers** [comment] 2019-04-18 16:38
@natemcmaster It looks like you referenced this issue from some commits. Did you make a fix relevant here?

**Comment by natemcmaster** [comment] 2019-04-18 16:59
No. These are false-positive matches which appear here as result mondo-repo merges. The commit messages are actually referring to https://github.com/aspnet/Diagnostics/pull/458 and https://github.com/aspnet/Localization/pull/458

**Comment by ajcvickers** [comment] 2019-04-18 17:00
Thanks Nate. That's what I suspected but wanted to check.

**Comment by derhally** [comment] 2019-05-18 11:04
We are running into this issue as well.   We have a container deployed to Kubernetes and have secrets that get updated periodically.  We have a callback registered via IOptionsMonitor.OnChange but it is never called back when the settings file is updated.   reloadOnChange was set to true when the settings file was added to the configuration.

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by MichaCo** [comment] 2019-06-26 14:44
Any update / solution on that? 
I'm running into the same issue that neither options monitor nor using the file provider monitoring manually, works on Linux based Azure App Services...

**Comment by derhally** [comment] 2019-06-26 15:31
The issue turns out to be related to how configmaps and secrets are made available.  There are multiple layers of symlinks involved and the watcher doesn't realize the settings have been updated.  This is the same issue as #1708 

Workaround is to use cause a rolling update of the pods.  Probably not the nicest option, there are k8s projects like https://github.com/stakater/Reloader and https://github.com/pusher/wave that do this.  I have not tried them out yet so I can't comment on them.

One other option is to calculate a checksum of the files on an interval and if the checksum changes force the config reload.

**Comment by Sacode** [comment] 2019-12-23 17:06
Duplicate of #1175

**Comment by anurse** [comment] 2020-01-30 19:55
Closing as duplicate of #1175

**Closed by anurse** 2020-01-30 19:55 UTC
Labels: area-options
