### ISSUE TITLE
IHostApplicationLifetime ApplicationStopping is not waiting on registrations

### ISSUE THREAD

**Issue by Pilchie** [dotnet/extensions#2827] opened 2020-01-05 23:51 UTC
_From @FrenkR on Saturday, January 4, 2020 10:19:02 AM_

# IHostApplicationLifetime ApplicationStopping is not waiting events

when registering IHostApplicationLifetime.ApplicationStopping event, event is called, but application stops before registered event is finished. According to documentation, application should wait for events (to be fully executed).

# Steps to reproduce

1.) create new "asp.net core web application" using standard VS template.

2.) inject "IHostApplicationLifetime" into "configure" method and register "applicationStopping" event:

`

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env, IHostApplicationLifetime hostApplicationLifetime )
        {
            app.UseRouting();
            app.UseAuthorization();
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
            hostApplicationLifetime.ApplicationStopping.Register(() =>
            {
                var _i = 0; // place debug breakpoint here!
                _i++;
            });

        }
 `

3.) start application in debug mode using "console" start. After starting, console window appears.
4.) set breakpoint inside "register" method. Then click "close"("x" on right upper corner of console application). You will notice that "applicationstopping" event is called, this is correct. But if you just wait on a breakpoint for 5-10 secons, you will notice that application has stopped without waiting for event to be executed. 
`

_Copied from original issue: dotnet/core#4072_

**Comment by Pilchie** [comment] 2020-01-05 23:51
_From @scalablecory on Sunday, January 5, 2020 1:39:49 AM_

The event is likely only triggered if you perform a graceful shutdown. @Pilchie

**Comment by Pilchie** [comment] 2020-01-05 23:51
_From @FrenkR on Sunday, January 5, 2020 8:25:08 AM_

event is triggered, but it does not block application termination.

**Comment by Tratcher** [comment] 2020-01-06 17:52
> But if you just wait on a breakpoint for 5-10 secons

That sounds like the HostOptions.ShutdownTimeout which defaults to 5 seconds. If you change the raise the shutdown timeout do you get different results?

**Comment by FrenkR** [comment] 2020-01-07 07:11
added here and there is no difference:

`
        public static void Main(string[] args)
        {
            CreateHostBuilder(args)
                .ConfigureServices((services) =>
                {
                    services.AddOptions<HostOptions>().Configure(
                        opts => opts.ShutdownTimeout = TimeSpan.FromSeconds(30));
                } )
                .Build().Run();
        }
`

**Comment by anurse** [comment] 2020-01-08 21:39
I think we're a little mixed up on some things here. @FrenkR please provide a runnable sample app that we can download/clone that reproduces the issue. Rather than a breakpoint (which does freeze the whole app and can mess with timers like this) I would suggest using something like `Thread.Sleep` to block the event handler.

In general, this seems like exactly the expected behavior to me. Shutdown is graceful to a point. It will allow you to block it for up to the timeout but if the timeout elapses, we'll stop the graceful shutdown process as soon as possible and terminate the app abruptly.

**Comment by FrenkR** [comment] 2020-01-08 22:03
[LifetimeBug.zip](https://github.com/dotnet/extensions/files/4037465/LifetimeBug.zip)
Sample is attached. ShutdownTimeout is set to 30 seconds, inside is event that lasts 25 seconds (thread.sleep()), but application still finishes in about 5 seconds.

**Comment by davidfowl** [comment] 2020-04-03 17:16
I can't reproduce this bug.

**Comment by FrenkR** [comment] 2020-04-03 17:21
which version do you have?

**Comment by davidfowl** [comment] 2020-04-03 18:49
3.1

**Comment by FrenkR** [comment] 2020-04-04 14:33
please do as follows. 
1. Run application. 
2. Then put breakpoint on a line 48 (inside anonymous funcion "applicationStopping event).
3. then click "X" in console window (close console), debugger should stop on a breakpoint
4. wait for 20 seconds and do nothing. You will see that application was stopped even if event was not finished.
What I understand is that application should wait for at least "ShutdownTimeout" before forced exit. But in this case, it exit much before.

**Comment by davidfowl** [comment] 2020-04-04 17:03
What happens if you hit control+c instead of pressing x

**Comment by FrenkR** [comment] 2020-04-04 17:20
heh, it is waiting :)

**Comment by FrenkR** [comment] 2020-04-04 17:23
so if CTRL+C is clicked, it works perfectly, if "X" is clicked, application does not wait for event to finish.

**Comment by davidfowl** [comment] 2020-04-04 18:51
Right, one is graceful (control + c), the other isn’t. There’s nothing you can do to handle ungraceful shutdown in the application.

**Comment by FrenkR** [comment] 2020-04-04 20:02
is there any option to prevent "X" on console app then or event to block "redirect" to graceful application stop?

**Comment by davidfowl** [comment] 2020-04-04 20:39
Why are you trying to optimize for somebody clicking X? There’s probably a Windows specific way to trap that specific click (assuming you don’t care about cross platform) but why does it matter? Are you also gonna try to handle killing the process in the task manager too?

**Comment by FrenkR** [comment] 2020-04-04 23:13
I have a modular application, sort of plugin system. Each plugin has defined "onStop" event that is triggered by a host. So when application is closed via "X" (everything except task-kill, which is obvious for me that there is no "exit" strategy except killing ASAP). host notifies plugin via  "onStop"event.  Plugin has a chance to properly shutdown himself and clean all resources. For example, if plugin starts external applications (processes) and monitors them, he must stop them before application shuts down. 
This event was for me obvious choice to detect "host" termination. The funniest thing is, that event is actually triggered even when clicking "X". Only problem is, that it does not wait for "shutdown timeout", nor this event to finish.

**Comment by davidfowl** [comment] 2020-04-05 00:01
I'm not sure that answers my question but AFAIK there's nothing you can do to stop the window from closing before your code completes.

**Comment by FrenkR** [comment] 2020-04-05 00:22
why? because most users (including me) click "X" instead of CTRL+C. Actually I don't know how this works on *ix, but I just would just expect that closing console would behave the same as closing via CTRL+C. Is there any other event, that would "wait" for "something to do" before application is shut down, regardless of a method of stopping application?

**Comment by davidfowl** [comment] 2020-04-05 00:33
Not that I'm aware of: 

```C#
using System;
using System.Threading;

namespace ConsoleApp4
{
    class Program
    {
        static void Main(string[] args)
        {
            AppDomain.CurrentDomain.ProcessExit += (sender, e) =>
            {
                Thread.Sleep(-1);
            };

            Console.CancelKeyPress += (sender, e) =>
            {
                Thread.Sleep(-1);
            };
        }
    }
}
```

Those are the features available to you in natively in .NET and neither of them have the effect you want.


A quick google search brought me to the following https://stackoverflow.com/questions/12117906/detect-when-console-is-being-closed. Maybe you can use this in your application?

**Comment by FrenkR** [comment] 2020-04-05 00:51
checked this one from stackoverflow. Same problem as with "applicationstopping" event. Fires, but after 5 seconds terminates application regardless what are you doing inside event. So conclusion so far is that I have 5 seconds to do something, then I am in any case dead.
Conceptually looking, it is quite strange that when you click "exe", new console window is opened. but then, when you click "X", application is terminated using "forced", "end task" way. Was there any special reason for such design?

**Comment by davidfowl** [comment] 2020-04-05 01:47
I have no idea. It’s a Windowsism.

**Comment by FrenkR** [comment] 2020-04-05 08:17
hehe, this can also be an explanation. But years ago we called something like that "a bug" and usually it was fixed too.
Thank you for your assistance and explanation :)

**Comment by davidfowl** [comment] 2020-04-05 16:36
@FrenkR let me know if you figure something out 😄. Regardless it might be something worth documenting.

**Comment by anurse** [comment] 2020-05-07 19:56
Looks similar to #2858 . The issue is that `Ctrl-C` is catchable but closing the window triggers `AppDomain.ProcessExit` which we really shouldn't block indefinitely.

**Closed** 2020-05-08 20:01 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Author: Migration Bot :robot:, Needs: Attention :wave:, Status: Resolved, area-hosting, routed

**Comment by FrenkR** [comment] 2020-05-08 21:36
what is the reason that AppDomain.ProcessExit dont "clean" everything same way as Ctrl+C does? There is "shutdowntimeout", that takes care of shutdown time?

**Comment by anurse** [comment] 2020-05-08 22:51
> what is the reason that AppDomain.ProcessExit dont "clean" everything same way as Ctrl+C does?

We actually **stop** the Ctrl-C (`Console.CancelKeyPress`) event from shutting down the process, because it provides that ability. So when Ctrl-C is pressed, we gracefully unwind and return control to wherever you called `IHost.RunAsync`. If you had code after `RunAsync`, it would run when Ctrl-C is pressed.

We can't cancel `ProcessExit`. We can trigger other code to run in other threads, but as soon as that event ends, the process will be terminated by the .NET runtime. So, we still signal for graceful shutdown (like in the Ctrl-C case), and we **synchronously block** waiting for the app to gracefully shut down. We can't do that indefinitely though, it would create a hang, so we only do it for a short period.

**Comment by FrenkR** [comment] 2020-05-09 06:07
is it possible to somehow override "ProcessExit" method and instead of "forced" shutdown, "redirect" it to regular Ctrl+C shutdown method?

**Comment by davidfowl** [comment] 2020-05-09 06:31
That would require a new feature in .NET itself.

**Comment by FrenkR** [comment] 2020-05-09 08:52
can you add it? I believe I am not the first and only person that have problems with this issue?
