### ISSUE TITLE
UseSystemd seems to interfere with UseConsoleLifetime

### ISSUE THREAD

**Issue by webczat** [dotnet/extensions#3163] opened 2020-04-07 21:40 UTC
Currently using dotnetcore sdk 3.1.200 and having some very hacky test aspnetcore app.
My goal is generally testing how things work, so I created a host that can be used as a standalone app, as systemd service, and as windows service.
I ran UseSystemd(), UseWindowsService() and UseConsoleLifetime() in this order. But it seems that even though my app runs as a normal console app, it nevertheless changes the console logging format.
Additionally if UseConsoleLifetime is first, then UseSystemd seems to override it because pressing ctrl+c does not do an orderly shutdown, I do not see log messages about host stopping. Does the systemd detection logic in UseSystemd malfunction?

**Comment by anurse** [comment] 2020-05-06 22:53
Can you provide a runnable sample project that reproduces the issues you're seeing? It's certainly possible that there's some ordering thing going on here, but it's hard to tell without specific code to look at that can demostrate the exact order of operations and behavior you're seeing.

**Comment by webczat** [comment] 2020-05-07 06:39
Hello,
Sorry I've forgotten about this issue, othervise I would likely provide an update:
This is not an ordering issue, it does not matter how you order these two calls at all.
The issue seemed to be detection of systemd, where the INVOCATION_ID or similar env variable was used to detect running under systemd.
I know that because the detection logic is fixed in master, tested that it was the cause by unsetting the env var in application before calling UseSystemd and it indeed worked.
I am not sure if this could be backported to 3.1 or not really? The relevant commit id seems to be cda774390962745f07baa11069f46aec489f4c61, I haven't directly tested that commit, just tried unsetting the envvar in app to see if it causes any difference.

**Comment by anurse** [comment] 2020-05-07 21:20
> I am not sure if this could be backported to 3.1 or not really?

No, it's not likely to meet the bar for backporting since there are workarounds (you can manually check the environment variable).

Given that, it sounds like this issue is resolved so I'm going to close it. Feel free to let us know if you have other context to provide that we're missing.

**Closed by anurse** 2020-05-07 21:20 UTC
Labels: Needs: Attention :wave:, area-hosting

**Comment by webczat** [comment] 2020-05-07 21:57
The problem seems to be that this doesn't happen rarely, this happens most of the time, that is when in linux desktop environments for example. Both when starting from vscode and directly from graphical terminal. So either an app has to document this or work around that itself by unsetting the env var or something like this. Ofc it only affects cases of running on console so development mostly or testing I'd say.
