### ISSUE TITLE
Add yaml configuration provider

### ISSUE THREAD

**Issue by webczat** [dotnet/extensions#2764] opened 2019-12-06 19:22 UTC
Hello.
Microsoft.Extensions.Configuration assemblies contain many configuration providers including ini, xml and json configuration. Also the json configuration is actually used as one of default config sources when creating hosts.
However, I propose to also add the yaml configuration provider. In my experience yaml is easier to read, understand and edit, is more human readable for the specific case of configuration files.
Json editing feels more error prone, for the reason of possible missing or extra commas or brackets, need to quote every name including json object keys, etc. My example is editing /etc/docker/daemon.json.

**Comment by gfoidl** [comment] 2019-12-07 12:43
See https://github.com/aspnet/Extensions/issues/2659, https://github.com/aspnet/Extensions/issues/1904, etc.

**Comment by Pilchie** [comment] 2020-01-23 17:18
Duplicate of #2659

**Closed by Pilchie** 2020-01-23 17:18 UTC
Labels: area-config
