### ISSUE TITLE
Support TypeConverterAttribute at ConfigurationBinder

### ISSUE THREAD

**Issue by GeorgeTsaplin** [dotnet/extensions#783] opened 2018-09-03 08:37 UTC
For example:
cats.json
```json
{
   "Cat": {
      "name": "Simon",
      "hasHair": 0
   }
}
```

```csharp
public class Cat
{
   public string Name { get; set; }
   public bool HasHair {get; set; }
}

public void Main()
{
   var configBuilder = new ConfigurationBuilder();

   var config = configBuilder.AddJsonFile("cats.json")
      .Build();

   var cat = config.GetSection("Cat").Get<Cat>();
```

Such code will fail because of converting "0" to bool.

To resolve this we can add such line of code before binding (`.Get<Cat>()`):
`TypeDescriptor.AddAttributes(typeof(Boolean), new TypeConverterAttribute(typeof(BooleanConverterEx))`.

But preferred way would be consider target type properties' TypeConverterAttribute. Configuration section POCO will be:
```csharp
public class Cat
{
   public string Name { get; set; }

   [TypeConverter(typeof(BooleanConverterEx))]
   public bool HasHair {get; set; }
}

    public class BooleanConverterEx : BooleanConverter
    {
        private static readonly IReadOnlyDictionary<string, bool> AllowedValues = new Dictionary<string, bool>(StringComparer.OrdinalIgnoreCase)
        {
            { "0", false },
            { "1", true }
        };

        public override object ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, object value)
        {
            bool result;
            if (AllowedValues.TryGetValue(value?.ToString(), out result))
            {
                return result;
            }

            return base.ConvertFrom(context, culture, value);
        }
    }
```

**Comment by anurse** [comment] 2020-03-10 18:05
Looks like a duplicate of https://github.com/dotnet/extensions/issues/497

**Closed** 2020-03-24 05:04 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-config
